export interface StoreCategory {
  id: string;
  name_ar: string;
  name_en: string;
  emoji: string;
}

export interface StoreBrand {
  id: string;
  category_id: string;
  name_ar: string;
  name_en: string;
  icon: string;
  desc: string;
}

export interface StoreProduct {
  id: string;
  short_id: string;
  brand_id: string;
  category_id: string;
  name: string;
  name_ar: string;
  button_title: string;
  icon_symbol: string;
  market_price: number;
  our_price: number;
  price_egp: number;
  price_sar: number;
  subscription_duration: string;
  warranty_duration: string;
  advantages_ar: string[];
}

export const STORE_CATEGORIES: StoreCategory[] = [
  { id: 'ai', name_ar: 'الذكاء الاصطناعي (AI)', name_en: 'Artificial Intelligence (AI)', emoji: '🤖' },
  { id: 'dev', name_ar: 'أدوات المطورين والبرمجة', name_en: 'Developer Tools', emoji: '💻' },
  { id: 'design', name_ar: 'التصميم والمونتاج', name_en: 'Design & Creative', emoji: '🎨' },
  { id: 'stream', name_ar: 'الترفيه والموسيقى', name_en: 'Streaming & Media', emoji: '🎬' },
  { id: 'vpn', name_ar: 'الحماية والـ VPN', name_en: 'Security & VPN', emoji: '🔐' },
  { id: 'prod', name_ar: 'الإنتاجية والأوفيس', name_en: 'Productivity & Office', emoji: '📚' },
];

export const STORE_BRANDS = [
  // AI
  { id: 'gemini', category_id: 'ai', name_ar: 'Google Gemini Advanced', name_en: 'Google Gemini Advanced', icon: '✦', desc: 'أحدث نماذج Gemini 3.1 Pro و Gemini 3.7 Flash مع 2TB سحابية' },
  { id: 'chatgpt', category_id: 'ai', name_ar: 'ChatGPT (OpenAI Plus/Pro/Team)', name_en: 'ChatGPT Plus/Pro/Team', icon: '🟢', desc: 'نماذج OpenAI o3-mini و o1 Pro Mode و GPT-4o مع الصوت المباشر' },
  { id: 'claude', category_id: 'ai', name_ar: 'Claude AI (Anthropic Pro/Team)', name_en: 'Claude AI Pro/Team', icon: '🟣', desc: 'نماذج Claude 3.7 Sonnet و Claude Opus 5 و Claude Fable 5 مع Hybrid Reasoning' },
  { id: 'perplexity', category_id: 'ai', name_ar: 'Perplexity AI Pro', name_en: 'Perplexity AI Pro', icon: '🌌', desc: 'البحث الأكاديمي والذكي بنماذج Sonar Reasoning Pro و Claude 3.7 و Deep Research' },
  { id: 'midjourney', category_id: 'ai', name_ar: 'Midjourney AI Imaging', name_en: 'Midjourney AI', icon: '🌟', desc: 'أعلى دقة لتوليد الصور والتصاميم الفنية بإصدارات v6.1 و Niji 6' },
  { id: 'elevenlabs', category_id: 'ai', name_ar: 'ElevenLabs Voice & Video AI', name_en: 'ElevenLabs Voice & Video AI', icon: '🎙️', desc: 'توليد أصوات بشرية فائقة واستنساخ صوتي ودبلجة بالـ AI' },
  { id: 'grok', category_id: 'ai', name_ar: 'Grok 3 / SuperGrok (xAI)', name_en: 'Grok 3 SuperGrok (xAI)', icon: '⚡', desc: 'أحدث نماذج Grok 3 مع Flux.1 وبيانات منصة X اللحظية' },
  { id: 'runway', category_id: 'ai', name_ar: 'Runway Gen-3 Video AI', name_en: 'Runway Gen-3 Video', icon: '🎬', desc: 'صناعة ومونتاج الفيديو السينمائي بالذكاء الاصطناعي Gen-3 Alpha & Turbo' },

  // DEV
  { id: 'cursor', category_id: 'dev', name_ar: 'Cursor AI (Pro & Ultra)', name_en: 'Cursor AI Pro & Ultra', icon: '💻', desc: 'محرر الأكواد الذكي بنماذج Claude 3.7 و Gemini 3.1 Pro و Composer Agent' },
  { id: 'copilot', category_id: 'dev', name_ar: 'GitHub Copilot & Student', name_en: 'GitHub Copilot & Student', icon: '🐙', desc: 'مساعد البرمجة الذكي داخل VS Code مع Copilot Chat' },
  { id: 'v0dev', category_id: 'dev', name_ar: 'v0.dev / Bolt.new Pro', name_en: 'v0.dev / Bolt.new Pro', icon: '⚡', desc: 'بناء واجهات وتطبيقات Fullstack الويب بالذكاء الاصطناعي' },
  { id: 'jetbrains', category_id: 'dev', name_ar: 'JetBrains All Products Pack', name_en: 'JetBrains All Products Pack', icon: '📦', desc: 'كل بيئات جيت برينز الـ 16 (IntelliJ, WebStorm, PyCharm)' },
  { id: 'replit', category_id: 'dev', name_ar: 'Replit Core & Agent Pro', name_en: 'Replit Core & Agent', icon: '🔥', desc: 'بيئة تطوير سحابية وبناء مشاريع ذاتية عبر Replit Agent Pro' },

  // DESIGN
  { id: 'canva', category_id: 'design', name_ar: 'Canva Pro (Magic Studio)', name_en: 'Canva Pro Magic Studio', icon: '🎨', desc: '100M+ قالب وتصميم مع كافة أدوات Magic Studio والذكاء الاصطناعي' },
  { id: 'capcut', category_id: 'design', name_ar: 'CapCut Pro (4K UHD)', name_en: 'CapCut Pro 4K UHD', icon: '✂️', desc: 'تصدير 4K بدون علامة مائية وفلاتر برو وترجمة تلقائية' },
  { id: 'adobe', category_id: 'design', name_ar: 'Adobe Creative Cloud All Apps', name_en: 'Adobe Creative Cloud', icon: '🟥', desc: '20+ تطبيق أدوبي كاملة (Photoshop, Premiere, Firefly AI)' },
  { id: 'figma', category_id: 'design', name_ar: 'Figma Professional', name_en: 'Figma Professional', icon: '🖌️', desc: 'تصميم واجهات وتجربة المستخدم للفرق مع Dev Mode' },
  { id: 'freepik', category_id: 'design', name_ar: 'Freepik Premium', name_en: 'Freepik Premium', icon: '📸', desc: 'ملايين الصور وملفات PSD والفيكتور الحصرية وترخيص تجاري' },
  { id: 'envato', category_id: 'design', name_ar: 'Envato Elements', name_en: 'Envato Elements', icon: '🎬', desc: 'تحميل غير محدود للقوالب والأكواد والموسيقى والفيديوهات' },

  // STREAMING
  { id: 'netflix', category_id: 'stream', name_ar: 'Netflix 4K UHD Ultra', name_en: 'Netflix 4K UHD Ultra', icon: '🎬', desc: 'أعلى جودة 4K Ultra HD مع صوت ثلاثي الأبعاد وبروفايل PIN' },
  { id: 'spotify', category_id: 'stream', name_ar: 'Spotify Premium', name_en: 'Spotify Premium', icon: '🎵', desc: 'استماع بدون إعلانات وتحميل أوفلاين وتشغيل في الخلفية' },
  { id: 'youtube', category_id: 'stream', name_ar: 'YouTube Premium + Music', name_en: 'YouTube Premium', icon: '▶️', desc: 'مشاهدة بدون إعلانات نهائياً وتشغيل بالخلفية وYouTube Music' },
  { id: 'disney', category_id: 'stream', name_ar: 'Disney+ Premium', name_en: 'Disney+ Premium', icon: '⭐', desc: 'أفلام ومسلسلات ديزني ومارفل بدقة 4K مع الدبلجة العربية' },
  { id: 'shahid', category_id: 'stream', name_ar: 'Shahid VIP Sports', name_en: 'Shahid VIP Sports', icon: '🍿', desc: 'بث مباشر للمباريات الرياضية ومسلسلات بدون فواصل بدقة FHD' },
  { id: 'discord', category_id: 'stream', name_ar: 'Discord Nitro Boost', name_en: 'Discord Nitro Boost', icon: '🎮', desc: '2 سيرفر بوست وإيموجي متحركة وبث 4K 60FPS ومميزات VIP' },
  { id: 'tgprem', category_id: 'stream', name_ar: 'Telegram Premium', name_en: 'Telegram Premium', icon: '✈️', desc: 'سرعة تنزيل فائقة وشارات مميزة ورفع 4GB وتحويل الصوت لنص' },

  // VPN & SECURITY
  { id: 'nordvpn', category_id: 'vpn', name_ar: 'NordVPN Plus', name_en: 'NordVPN Plus', icon: '🛡️', desc: 'حماية وتشفير وتخطي الحجب بسرعات فائقة في 111 دولة' },
  { id: 'expressvpn', category_id: 'vpn', name_ar: 'ExpressVPN Ultra', name_en: 'ExpressVPN Ultra', icon: '⚡', desc: 'أسرع بروتوكول Lightway وخوادم في 105 دولة مع ثبات مطلق' },
  { id: 'surfshark', category_id: 'vpn', name_ar: 'Surfshark One', name_en: 'Surfshark One', icon: '🦈', desc: 'أجهزة غير محدودة مع حماية كاملة ومضاد فيروسات CleanWeb' },
  { id: 'kaspersky', category_id: 'vpn', name_ar: 'Kaspersky Total Security', name_en: 'Kaspersky Total Security', icon: '🔐', desc: 'مفتاح ترخيص أصلي وحماية شاملة من الفيروسات وجدار ناري' },

  // PRODUCTIVITY & OFFICE
  { id: 'notion', category_id: 'prod', name_ar: 'Notion AI Plus', name_en: 'Notion AI Plus', icon: '📝', desc: 'تنظيم المهام والملاحظات مع ذكاء اصطناعي غير محدود ومزامنة' },
  { id: 'grammarly', category_id: 'prod', name_ar: 'Grammarly Premium', name_en: 'Grammarly Premium', icon: '🔤', desc: 'تدقيق لغوي وصياغة احترافية وفحص الاقتباس والانتحال الأدبي' },
  { id: 'duolingo', category_id: 'prod', name_ar: 'Duolingo Super', name_en: 'Duolingo Super', icon: '📚', desc: 'تعلم اللغات بقلوب وطاقة غير محدودة وبدون إعلانات' },
  { id: 'm365', category_id: 'prod', name_ar: 'Microsoft 365 + 1TB', name_en: 'Microsoft 365 + 1TB', icon: '📊', desc: 'Word, Excel, PowerPoint مع 1TB سحابي OneDrive لـ 5 أجهزة' },
  { id: 'win11', category_id: 'prod', name_ar: 'Windows 11 Pro Retail', name_en: 'Windows 11 Pro Retail Key', icon: '🪟', desc: 'مفتاح تفعيل أصلي دائم مدى الحياة يقبل التحديثات وإعادة التثبيت' },
];

export const STORE_CATALOG = [
  // ── 1. GOOGLE GEMINI ──
  {
    id: 'gemini_1m_prod',
    short_id: 'gemini_1m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 1m',
    name_ar: 'Google Gemini Advanced (شهر كامل)',
    button_title: '✦ Gemini (شهر واحد) — $3.49 ⚡',
    icon_symbol: '✦',
    market_price: 19.99,
    our_price: 3.49,
    price_egp: 175,
    price_sar: 13,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أحدث نماذج Gemini 3.1 Pro و Gemini 3.7 Flash و 2.5 Pro', 'مساحة تخزين سحابية ضخمة 2TB على Google One', 'تكامل كامل مع Google Workspace والبحث المعمق Deep Research', 'ضمان استبدال فوري 100% طوال المدة'],
  },
  {
    id: 'gemini_3m_prod',
    short_id: 'gemini_3m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 3m',
    name_ar: 'Google Gemini Advanced (3 شهور)',
    button_title: '✦ Gemini (3 شهور) — $7.99 ⚡',
    icon_symbol: '✦',
    market_price: 59.99,
    our_price: 7.99,
    price_egp: 399,
    price_sar: 30,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['أحدث نماذج Gemini 3.1 Pro المتقدمة للبرمجة والتفكير المعقد', 'مساحة تخزين 2TB Google One سحابية مشتركة', 'دعم كتابة الأكواد والتحليل البياني المتقدم', 'ضمان استبدال رسمي طوال 3 شهور'],
  },
  {
    id: 'gemini_12m_prod',
    short_id: 'gemini_12m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 12m',
    name_ar: 'Google Gemini Advanced (سنة كاملة)',
    button_title: '✦ Gemini (سنة كاملة) — $24.99 ⚡',
    icon_symbol: '✦',
    market_price: 239.99,
    our_price: 24.99,
    price_egp: 1250,
    price_sar: 94,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل مدعوم بمنظومة Antigravity و AI Studio', '2 تيرابايت تخزين سحابي Google One أصلي خاص', 'أولوية قصوى عند إطلاق تحديثات نماذج Gemini الجديدة', 'ضمان استبدال سنوي شامل 100%'],
  },

  // ── 2. CHATGPT & OPENAI ──
  {
    id: 'chatgpt_1m_prod',
    short_id: 'chatgpt_1m',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 1m',
    name_ar: 'ChatGPT Plus (شهر كامل)',
    button_title: '🟢 ChatGPT Plus (شهر واحد) — $4.99 ⚡',
    icon_symbol: '🟢',
    market_price: 20.00,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['نماذج GPT-4o و OpenAI o3-mini High و o1 Pro', 'توليد الصور بدقة فائقة عبر DALL-E 3', 'الوضع الصوتي المتقدم Advanced Voice Mode لحظياً', 'إنشاء واستخدام مئات الـ GPTs المخصصة'],
  },
  {
    id: 'chatgpt_3m_prod',
    short_id: 'chatgpt_3m',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 3m',
    name_ar: 'ChatGPT Plus (3 شهور)',
    button_title: '🟢 ChatGPT Plus (3 شهور) — $12.99 ⚡',
    icon_symbol: '🟢',
    market_price: 60.00,
    our_price: 12.99,
    price_egp: 650,
    price_sar: 49,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['استخدام غير محدود ومستقر لنماذج GPT-4o و o3-mini', 'أولوية قصوى والوصول أثناء أوقات الذروة العالمية', 'دعم تحليل البيانات والبرمجة التلقائية', 'ضمان استبدال فوري 100% طوال 3 شهور'],
  },
  {
    id: 'chatgpt_12m_prod',
    short_id: 'chatgpt_12m',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 12m',
    name_ar: 'ChatGPT Plus (سنة كاملة)',
    button_title: '🟢 ChatGPT Plus (سنة كاملة) — $42.99 ⚡',
    icon_symbol: '🟢',
    market_price: 240.00,
    our_price: 42.99,
    price_egp: 2150,
    price_sar: 161,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['توفير هائل للتجار والمطورين طوال عام كامل', 'وصول غير محدود لجميع أدوات OpenAI المتطورة وتحديثاتها', 'حساب خاص ومستقر بالكامل مع دعم مخصص', 'ضمان استبدال رسمي سنوي شامل'],
  },
  {
    id: 'chatgpt_pro_prod',
    short_id: 'chatgpt_pro',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Pro 1m',
    name_ar: 'ChatGPT Pro (أعلى باقة قوة حوسبة)',
    button_title: '🟢 ChatGPT Pro (شهر كامل) — $39.99 ⚡',
    icon_symbol: '🟢',
    market_price: 200.00,
    our_price: 39.99,
    price_egp: 2000,
    price_sar: 150,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['وصول غير محدود لنموذج OpenAI o1 Pro Mode بأعلى قدرة تفكير وحوسبة', 'وصول غير محدود للنموذج الأقوى GPT-4o', 'الوضع الصوتي المتقدم بدون حدود استهلاك', 'مخصص للباحثين والمهندسين والشركات'],
  },

  // ── 3. CLAUDE AI ──
  {
    id: 'claude_1m_prod',
    short_id: 'claude_1m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 1m',
    name_ar: 'Claude AI Pro (شهر كامل)',
    button_title: '🟣 Claude Pro (شهر واحد) — $4.99 ⚡',
    icon_symbol: '🟣',
    market_price: 20.00,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أحدث نماذج Claude 3.7 Sonnet و Claude Opus 5 و Claude Fable 5', 'ميزة التفكير الهجين Hybrid Reasoning وميزة Claude Code CLI', 'نافذة سياق ضخمة 200K لمعالجة مستندات وأكواد عملاقة', '5 أضعاف الاستهلاك مقارنة بالخطة المجانية'],
  },
  {
    id: 'claude_3m_prod',
    short_id: 'claude_3m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 3m',
    name_ar: 'Claude AI Pro (3 شهور)',
    button_title: '🟣 Claude Pro (3 شهور) — $12.99 ⚡',
    icon_symbol: '🟣',
    market_price: 60.00,
    our_price: 12.99,
    price_egp: 650,
    price_sar: 49,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['أداء منقطع النظير في كتابة الأكواد والتحليل المنطقي والبحث', 'مشاريع Projects ومكتبات Artifacts مخصصة ومزامنة كاملة', 'أولوية مطلقة أثناء أوقات الذروة', 'ضمان استبدال رسمي 100% طوال 3 شهور'],
  },
  {
    id: 'claude_12m_prod',
    short_id: 'claude_12m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 12m',
    name_ar: 'Claude AI Pro (سنة كاملة)',
    button_title: '🟣 Claude Pro (سنة كاملة) — $44.99 ⚡',
    icon_symbol: '🟣',
    market_price: 240.00,
    our_price: 44.99,
    price_egp: 2250,
    price_sar: 169,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['الخيار الأقوى للمطورين وصناع المحتوى والباحثين طوال عام كامل', 'تحديثات مستمرة لكافة نماذج Anthropic الصادرة حديثاً', 'حساب رسمي خاص ومستقر تماماً', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 4. PERPLEXITY AI ──
  {
    id: 'perplexity_1m_prod',
    short_id: 'perplexity_1m',
    brand_id: 'perplexity',
    category_id: 'ai',
    name: 'Perplexity Pro 1m',
    name_ar: 'Perplexity AI Pro (شهر كامل)',
    button_title: '🌌 Perplexity Pro (شهر واحد) — $3.99 ⚡',
    icon_symbol: '🌌',
    market_price: 20.00,
    our_price: 3.99,
    price_egp: 200,
    price_sar: 15,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['محرك البحث الأذكى في العالم مع مصادر وروابط موثقة لحظياً', 'استخدام نماذج Sonar Reasoning Pro و Claude 3.7 و GPT-4o', 'رفع وتحليل ملفات PDF والأكواد غير محدود', 'ميزة Deep Research المتقدمة'],
  },
  {
    id: 'perplexity_12m_prod',
    short_id: 'perplexity_12m',
    brand_id: 'perplexity',
    category_id: 'ai',
    name: 'Perplexity Pro 12m',
    name_ar: 'Perplexity AI Pro (سنة كاملة)',
    button_title: '🌌 Perplexity Pro (سنة كاملة) — $29.99 ⚡',
    icon_symbol: '🌌',
    market_price: 200.00,
    our_price: 29.99,
    price_egp: 1500,
    price_sar: 112,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['بحث أكاديمي ومهني فائق الذكاء طوال عام كامل', 'أكثر من 600+ استعلام Pro يومياً مع توليد الصور بالـ AI', 'توفير يتجاوز 85% من السعر الرسمي', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 5. MIDJOURNEY AI ──
  {
    id: 'midjourney_basic_prod',
    short_id: 'midjourney_basic',
    brand_id: 'midjourney',
    category_id: 'ai',
    name: 'Midjourney Basic 1m',
    name_ar: 'Midjourney Basic (شهر كامل)',
    button_title: '🌟 Midjourney Basic (شهر واحد) — $3.99 ⚡',
    icon_symbol: '🌟',
    market_price: 10.00,
    our_price: 3.99,
    price_egp: 200,
    price_sar: 15,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['3.3 ساعات توليد سريع Fast GPU Hours (حوالي 200 صورة فائقة الجودة)', 'أحدث إصدارات Midjourney v6.1 و Niji v6 للأنمي والفن', 'أدوات التكبير والتعديل Inpainting و Pan و Zoom', 'ترخيص تجاري كامل للصور'],
  },
  {
    id: 'midjourney_standard_prod',
    short_id: 'midjourney_std',
    brand_id: 'midjourney',
    category_id: 'ai',
    name: 'Midjourney Standard 1m',
    name_ar: 'Midjourney Standard (شهر كامل)',
    button_title: '🌟 Midjourney Standard (شهر واحد) — $9.99 ⚡',
    icon_symbol: '🌟',
    market_price: 30.00,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['15 ساعة توليد سريع Fast GPU شهرياً', 'توليد غير محدود في وضع Relax GPU بدون حدود', 'الوصول لموقع Midjourney Alpha ومكتبة الأعمال', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'midjourney_12m_prod',
    short_id: 'midjourney_12m',
    brand_id: 'midjourney',
    category_id: 'ai',
    name: 'Midjourney Standard 12m',
    name_ar: 'Midjourney Standard (سنة كاملة)',
    button_title: '🌟 Midjourney (سنة كاملة) — $79.99 ⚡',
    icon_symbol: '🌟',
    market_price: 360.00,
    our_price: 79.99,
    price_egp: 4000,
    price_sar: 300,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['الاشتراك الأفضل للمصممين والاستوديوهات وصناع المحتوى', 'توليد غير محدود ومستقر على مدار السنة', 'ترخيص تجاري لكافة الأعمال المنتجة', 'ضمان سنوي رسمي شامل'],
  },

  // ── 6. ELEVENLABS AI ──
  {
    id: 'elevenlabs_starter_prod',
    short_id: 'elevenlabs_starter',
    brand_id: 'elevenlabs',
    category_id: 'ai',
    name: 'ElevenLabs Starter 1m',
    name_ar: 'ElevenLabs Starter (شهر كامل)',
    button_title: '🎙️ ElevenLabs Starter (شهر واحد) — $2.99 ⚡',
    icon_symbol: '🎙️',
    market_price: 5.00,
    our_price: 2.99,
    price_egp: 150,
    price_sar: 11,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['30,000 حرف شهرياً بنقاء صوت استوديو فائق', 'إنشاء واستنساخ 10 أصوات مخصصة Instant Voice Cloning', 'دعم أكثر من 29 لغة منها العربية الطبيعية', 'ترخيص تجاري رسمي'],
  },
  {
    id: 'elevenlabs_creator_prod',
    short_id: 'elevenlabs_creator',
    brand_id: 'elevenlabs',
    category_id: 'ai',
    name: 'ElevenLabs Creator 1m',
    name_ar: 'ElevenLabs Creator (شهر كامل)',
    button_title: '🎙️ ElevenLabs Creator (شهر واحد) — $8.99 ⚡',
    icon_symbol: '🎙️',
    market_price: 22.00,
    our_price: 8.99,
    price_egp: 450,
    price_sar: 34,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['100,000 حرف شهرياً مع جودة 192kbps استوديو', 'استنساخ أصوات احترافي Professional Voice Cloning', 'دبلجة الفيديو التلقائية بالذكاء الاصطناعي', 'ضمان استبدال رسمي 100%'],
  },

  // ── 7. GROK 3 (xAI) ──
  {
    id: 'grok_1m_prod',
    short_id: 'grok_1m',
    brand_id: 'grok',
    category_id: 'ai',
    name: 'Grok 3 SuperGrok 1m',
    name_ar: 'Grok 3 / SuperGrok (شهر كامل)',
    button_title: '⚡ Grok 3 (شهر واحد) — $4.49 ⚡',
    icon_symbol: '⚡',
    market_price: 16.00,
    our_price: 4.49,
    price_egp: 225,
    price_sar: 17,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أحدث نماذج Grok 3 و Grok 3 Think (DeepSearch)', 'توليد وتعديل الصور المتقدم عبر Flux.1', 'بيانات ومعلومات لحظية ومباشرة من منصة X (تويتر)', 'شارة التوثيق الزرقاء وجميع مميزات X Premium+'],
  },
  {
    id: 'grok_12m_prod',
    short_id: 'grok_12m',
    brand_id: 'grok',
    category_id: 'ai',
    name: 'Grok 3 SuperGrok 12m',
    name_ar: 'Grok 3 / SuperGrok (سنة كاملة)',
    button_title: '⚡ Grok 3 (سنة كاملة) — $39.99 ⚡',
    icon_symbol: '⚡',
    market_price: 168.00,
    our_price: 39.99,
    price_egp: 2000,
    price_sar: 150,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل في منظومة xAI و Premium+', 'توليد غير محدود للأفكار والتحليلات والصور', 'ضمان استبدال سنوي شامل 100%'],
  },

  // ── 8. RUNWAY GEN-3 VIDEO AI ──
  {
    id: 'runway_standard_prod',
    short_id: 'runway_std',
    brand_id: 'runway',
    category_id: 'ai',
    name: 'Runway Gen-3 Standard 1m',
    name_ar: 'Runway Gen-3 Standard (شهر كامل)',
    button_title: '🎬 Runway Gen-3 (شهر واحد) — $5.99 ⚡',
    icon_symbol: '🎬',
    market_price: 15.00,
    our_price: 5.99,
    price_egp: 300,
    price_sar: 22,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['625 نقطة رصيد شهرياً لتوليد الفيديو بدقة 4K', 'محرك Gen-3 Alpha و Gen-3 Turbo لصناعة المشاهد السينمائية', 'ميزات تحريك الصور Text-to-Video و Image-to-Video', 'تصدير فيديو بدون علامات مائية وبدقة عالية'],
  },

  // ── 9. CURSOR AI ──
  {
    id: 'cursor_1m_prod',
    short_id: 'cursor_1m',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 1m',
    name_ar: 'Cursor AI Pro (شهر كامل)',
    button_title: '💻 Cursor Pro (شهر واحد) — $4.99 ⚡',
    icon_symbol: '💻',
    market_price: 20.00,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['500 طلب سريع Fast Premium شهرياً بنماذج Claude 3.7 و Gemini 3.1 Pro', 'إكمال تلقائي ذكي غير محدود Tab Autocomplete مع فهم كامل للمشروع', 'أدوات Composer Agent المتقدمة لتطوير وبناء الملفات تلقائياً', 'فهرسة دلالية كاملة للمشروع Codebase Indexing'],
  },
  {
    id: 'cursor_12m_prod',
    short_id: 'cursor_12m',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 12m',
    name_ar: 'Cursor AI Pro (سنة كاملة)',
    button_title: '💻 Cursor Pro (سنة كاملة) — $44.99 ⚡',
    icon_symbol: '💻',
    market_price: 240.00,
    our_price: 44.99,
    price_egp: 2250,
    price_sar: 169,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['البيئة الاحترافية الأولى للمبرمجين ومهندسي البرمجيات طوال عام كامل', 'استخدام غير محدود ومستمر لكافة نماذج الذكاء الاصطناعي البرمجية', 'توفير هائل يتجاوز 80%', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 10. GITHUB COPILOT ──
  {
    id: 'copilot_1m_prod',
    short_id: 'copilot_1m',
    brand_id: 'copilot',
    category_id: 'dev',
    name: 'GitHub Copilot 1m',
    name_ar: 'GitHub Copilot Pro (شهر كامل)',
    button_title: '🐙 GitHub Copilot (شهر واحد) — $3.49 ⚡',
    icon_symbol: '🐙',
    market_price: 10.00,
    our_price: 3.49,
    price_egp: 175,
    price_sar: 13,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['مساعد برمجي متكامل داخل VS Code و JetBrains و Neovim', 'شات Copilot Chat المباشر لحل المشكلات وكتابة الاختبارات', 'اقتراحات برمجية سريعة ودقيقة في الوقت الفعلي', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'copilot_12m_prod',
    short_id: 'copilot_12m',
    brand_id: 'copilot',
    category_id: 'dev',
    name: 'GitHub Copilot 12m',
    name_ar: 'GitHub Copilot Pro (سنة كاملة)',
    button_title: '🐙 GitHub Copilot (سنة كاملة) — $24.99 ⚡',
    icon_symbol: '🐙',
    market_price: 100.00,
    our_price: 24.99,
    price_egp: 1250,
    price_sar: 94,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['ترخيص رسمي سنوي مخصص على حسابك أو حساب جاهز', 'مساعدة برمجية متواصلة على مدار عام كامل', 'ضمان استبدال سنوي شامل'],
  },

  // ── 11. V0.DEV / BOLT.NEW ──
  {
    id: 'v0dev_1m_prod',
    short_id: 'v0dev_1m',
    brand_id: 'v0dev',
    category_id: 'dev',
    name: 'v0.dev Pro 1m',
    name_ar: 'v0.dev / Bolt.new Pro (شهر كامل)',
    button_title: '⚡ v0.dev Pro (شهر واحد) — $5.99 ⚡',
    icon_symbol: '⚡',
    market_price: 20.00,
    our_price: 5.99,
    price_egp: 300,
    price_sar: 22,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['بناء وتصميم واجهات وتطبيقات React و Next.js و Tailwind فورياً بالـ AI', '5,000 نقطة توليد شهرياً مع تصدير الأكواد بضغطة زر', 'نشر وتجربة التطبيقات السحابية فورياً', 'ضمان استبدال رسمي 100%'],
  },

  // ── 12. JETBRAINS ALL PRODUCTS ──
  {
    id: 'jetbrains_12m_prod',
    short_id: 'jetbrains_12m',
    brand_id: 'jetbrains',
    category_id: 'dev',
    name: 'JetBrains All Products 12m',
    name_ar: 'JetBrains All Products Pack (سنة كاملة)',
    button_title: '📦 JetBrains Pack (سنة كاملة) — $14.99 ⚡',
    icon_symbol: '📦',
    market_price: 289.00,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['يشمل جميع بيئات JetBrains الـ 16 (IntelliJ IDEA Ultimate, WebStorm, PyCharm Pro, PhpStorm, CLion, Rider)', 'ترخيص رسمي مفعل ومستقر طوال عام كامل', 'توفير يتجاوز 95% عن السعر الرسمي', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 13. REPLIT CORE & AGENT ──
  {
    id: 'replit_1m_prod',
    short_id: 'replit_1m',
    brand_id: 'replit',
    category_id: 'dev',
    name: 'Replit Core & Agent 1m',
    name_ar: 'Replit Core & Agent Pro (شهر كامل)',
    button_title: '🔥 Replit Core (شهر واحد) — $6.99 ⚡',
    icon_symbol: '🔥',
    market_price: 25.00,
    our_price: 6.99,
    price_egp: 350,
    price_sar: 26,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['وصول كامل لـ Replit Agent لبناء تطبيقات كاملة ذاتياً بالأوامر النصية', 'مساحات عمل سحابية قوية مع 4x Storage و 4x Speed', 'استضافة وتشغيل السيرفرات والبوتات 24/7 Always-On', 'ضمان استبدال فوري 100%'],
  },

  // ── 14. CANVA PRO ──
  {
    id: 'canva_12m_prod',
    short_id: 'canva_12m',
    brand_id: 'canva',
    category_id: 'design',
    name: 'Canva Pro 12m',
    name_ar: 'Canva Pro (سنة كاملة)',
    button_title: '🎨 Canva Pro (سنة كاملة) — $2.99 ⚡',
    icon_symbol: '🎨',
    market_price: 120.00,
    our_price: 2.99,
    price_egp: 150,
    price_sar: 11,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['أكثر من 100+ مليون صورة وفيديو وقالب وتصميم مدفوع متاح مجاناً', 'كافة أدوات Magic Studio والذكاء الاصطناعي وإزالة الخلفية بضغطة زر', 'تفعيل رسمي خاص على إيميلك الشخصي', 'ضمان استبدال سنوي رسمي 100%'],
  },
  {
    id: 'canva_lifetime_prod',
    short_id: 'canva_lifetime',
    brand_id: 'canva',
    category_id: 'design',
    name: 'Canva Pro Lifetime VIP',
    name_ar: 'Canva Pro (مدى الحياة VIP)',
    button_title: '🎨 Canva Pro (مدى الحياة) — $5.99 ⚡',
    icon_symbol: '🎨',
    market_price: 300.00,
    our_price: 5.99,
    price_egp: 300,
    price_sar: 22,
    subscription_duration: 'وصول دائم مدى الحياة',
    warranty_duration: 'ضمان رسمي مدى الحياة',
    advantages_ar: ['اشتراك دائم ومستمر على إيميلك الشخصي مدى الحياة', 'مساحة تخزين سحابية ضخمة لحفظ مشاريعك وتصاميمك', 'توفير نهائي دون أي تجديدات شهرية أو سنوية', 'ضمان استبدال رسمي دائم'],
  },

  // ── 15. CAPCUT PRO ──
  {
    id: 'capcut_1m_prod',
    short_id: 'capcut_1m',
    brand_id: 'capcut',
    category_id: 'design',
    name: 'CapCut Pro 1m',
    name_ar: 'CapCut Pro (شهر كامل)',
    button_title: '✂️ CapCut Pro (شهر واحد) — $2.49 ⚡',
    icon_symbol: '✂️',
    market_price: 9.99,
    our_price: 2.49,
    price_egp: 125,
    price_sar: 9,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['تصدير الفيديو بدقة 4K 60fps و HDR بدون علامة مائية', 'الترجمة التلقائية الذكية Auto Captions بدقة متناهية للعربية', 'كافة الانتقالات والفلاتر ومؤثرات الذكاء الاصطناعي المدفوعة', 'يعمل على PC و Mac و iPhone و Android'],
  },
  {
    id: 'capcut_12m_prod',
    short_id: 'capcut_12m',
    brand_id: 'capcut',
    category_id: 'design',
    name: 'CapCut Pro 12m',
    name_ar: 'CapCut Pro (سنة كاملة)',
    button_title: '✂️ CapCut Pro (سنة كاملة) — $14.99 ⚡',
    icon_symbol: '✂️',
    market_price: 89.99,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['الحل الأفضل والمستمر لصناع المحتوى واليوتيوبرز ومحرري الفيديو', '100GB تخزين سحابي للمشاريع والمسودات', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 16. ADOBE CREATIVE CLOUD ──
  {
    id: 'adobe_1m_prod',
    short_id: 'adobe_1m',
    brand_id: 'adobe',
    category_id: 'design',
    name: 'Adobe All Apps 1m',
    name_ar: 'Adobe Creative Cloud (شهر كامل)',
    button_title: '🟥 Adobe All Apps (شهر واحد) — $9.99 ⚡',
    icon_symbol: '🟥',
    market_price: 59.99,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['يشمل كافة برامج أدوبي الـ 20+ كاملة (Photoshop, Premiere, Illustrator, After Effects)', 'توليد الذكاء الاصطناعي Adobe Firefly ونقاط Generative Credits', 'تفعيل على إيميلك الشخصي أو حساب جاهز مع 100GB سحابي', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'adobe_3m_prod',
    short_id: 'adobe_3m',
    brand_id: 'adobe',
    category_id: 'design',
    name: 'Adobe All Apps 3m',
    name_ar: 'Adobe Creative Cloud (3 شهور)',
    button_title: '🟥 Adobe All Apps (3 شهور) — $24.99 ⚡',
    icon_symbol: '🟥',
    market_price: 179.99,
    our_price: 24.99,
    price_egp: 1250,
    price_sar: 94,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['ترخيص رسمي متواصل لـ 3 شهور بدون أي انقطاع', 'تحديثات البرامج التلقائية من Adobe Creative Cloud Desktop', 'ضمان استبدال رسمي طوال 3 شهور'],
  },
  {
    id: 'adobe_12m_prod',
    short_id: 'adobe_12m',
    brand_id: 'adobe',
    category_id: 'design',
    name: 'Adobe All Apps 12m',
    name_ar: 'Adobe Creative Cloud (سنة كاملة)',
    button_title: '🟥 Adobe All Apps (سنة كاملة) — $69.99 ⚡',
    icon_symbol: '🟥',
    market_price: 659.00,
    our_price: 69.99,
    price_egp: 3500,
    price_sar: 262,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['الاشتراك السنوي الأكثر طلباً للوكالات الإعلانية والمصممين المحترفين', 'توفير يتجاوز 90% مع ضمان رسمي كامل المدة', 'دعم خطوط Adobe Fonts ومكتبات Creative Cloud Libraries', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 17. FIGMA PROFESSIONAL ──
  {
    id: 'figma_12m_prod',
    short_id: 'figma_12m',
    brand_id: 'figma',
    category_id: 'design',
    name: 'Figma Professional 12m',
    name_ar: 'Figma Professional (سنة كاملة)',
    button_title: '🖌️ Figma Pro (سنة كاملة) — $14.99 ⚡',
    icon_symbol: '🖌️',
    market_price: 144.00,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مشاريع غير محدودة وتاريخ نسخ غير محدود للملفات', 'ميزات Dev Mode لتصدير الأكواد للمطورين', 'مكتبات ومكونات الفريق المشتركة Team Component Libraries', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 18. FREEPIK PREMIUM ──
  {
    id: 'freepik_1m_prod',
    short_id: 'freepik_1m',
    brand_id: 'freepik',
    category_id: 'design',
    name: 'Freepik Premium 1m',
    name_ar: 'Freepik Premium (شهر كامل)',
    button_title: '📸 Freepik Premium (شهر واحد) — $3.49 ⚡',
    icon_symbol: '📸',
    market_price: 15.00,
    our_price: 3.49,
    price_egp: 175,
    price_sar: 13,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['100 تحميل يومياً لملفات الفيكتور الحصرية والصور وملفات PSD و 3D', 'ترخيص تجاري كامل للمشاريع والعملاء', 'تصفح بدون إعلانات نهائياً', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'freepik_12m_prod',
    short_id: 'freepik_12m',
    brand_id: 'freepik',
    category_id: 'design',
    name: 'Freepik Premium 12m',
    name_ar: 'Freepik Premium (سنة كاملة)',
    button_title: '📸 Freepik Premium (سنة كاملة) — $19.99 ⚡',
    icon_symbol: '📸',
    market_price: 140.00,
    our_price: 19.99,
    price_egp: 1000,
    price_sar: 75,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مكتبة جرافيك لا نهائية متاحة طوال عام كامل', 'توفير يتجاوز 85% مع استقرار وثبات عالي', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 19. ENVATO ELEMENTS ──
  {
    id: 'envato_1m_prod',
    short_id: 'envato_1m',
    brand_id: 'envato',
    category_id: 'design',
    name: 'Envato Elements 1m',
    name_ar: 'Envato Elements (شهر كامل)',
    button_title: '🎬 Envato Elements (شهر واحد) — $4.99 ⚡',
    icon_symbol: '🎬',
    market_price: 33.00,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['تحميل غير محدود لقوالب الفيديو، الموسيقى، المؤثرات، الخطوط، وقوالب WordPress', 'ترخيص تجاري فوري لكل عنصر تقوم بتحميله', 'المكتبة الأضخم لصناع المحتوى ومطوري المواقع', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'envato_12m_prod',
    short_id: 'envato_12m',
    brand_id: 'envato',
    category_id: 'design',
    name: 'Envato Elements 12m',
    name_ar: 'Envato Elements (سنة كاملة)',
    button_title: '🎬 Envato Elements (سنة كاملة) — $29.99 ⚡',
    icon_symbol: '🎬',
    market_price: 198.00,
    our_price: 29.99,
    price_egp: 1500,
    price_sar: 112,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عام كامل من التحميلات غير المحدودة لجميع موارد التصميم والويب', 'توفير يتجاوز 85% مقارنة بالاشتراك المباشر', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 20. NETFLIX 4K UHD ──
  {
    id: 'netflix_1m_prod',
    short_id: 'netflix_1m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 1m',
    name_ar: 'Netflix 4K Ultra HD (شهر كامل)',
    button_title: '🎬 Netflix 4K (شهر واحد) — $2.99 ⚡',
    icon_symbol: '🎬',
    market_price: 22.99,
    our_price: 2.99,
    price_egp: 150,
    price_sar: 11,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أعلى جودة بث Ultra HD 4K مع تقنيات HDR و Spatial Audio', 'ملف شخصي Profile خاص مقفل برمز PIN سري خاص بك', 'يعمل على الشاشات الذكية، الهواتف، اللابتوب و Apple TV', 'بدون أي تعارض في المشاهدة مع ضمان استبدال فوري 100%'],
  },
  {
    id: 'netflix_3m_prod',
    short_id: 'netflix_3m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 3m',
    name_ar: 'Netflix 4K Ultra HD (3 شهور)',
    button_title: '🎬 Netflix 4K (3 شهور) — $7.99 ⚡',
    icon_symbol: '🎬',
    market_price: 68.99,
    our_price: 7.99,
    price_egp: 400,
    price_sar: 30,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['مشاهدة مستقرة بدون انقطاع طوال 3 شهور كاملة', 'بروفايل خاص دائم مع حفظ قائمة المفضلة وتاريخ المشاهدة', 'ضمان استبدال رسمي 100% طوال المدة'],
  },
  {
    id: 'netflix_6m_prod',
    short_id: 'netflix_6m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 6m',
    name_ar: 'Netflix 4K Ultra HD (6 شهور)',
    button_title: '🎬 Netflix 4K (6 شهور) — $14.99 ⚡',
    icon_symbol: '🎬',
    market_price: 137.99,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['نصف سنة كاملة من المشاهدة المستمرة بأعلى دقة 4K', 'ثبات مطلق ودعم فني مخصص', 'ضمان استبدال شامل 100% طوال 6 شهور'],
  },
  {
    id: 'netflix_12m_prod',
    short_id: 'netflix_12m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 12m',
    name_ar: 'Netflix 4K Ultra HD (سنة كاملة)',
    button_title: '🎬 Netflix 4K (سنة كاملة) — $26.99 ⚡',
    icon_symbol: '🎬',
    market_price: 275.99,
    our_price: 26.99,
    price_egp: 1350,
    price_sar: 101,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل ومستقر بملفك الخاص طوال عام', 'توفير هائل يتجاوز 90% عن السعر الرسمي', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 21. SPOTIFY PREMIUM ──
  {
    id: 'spotify_1m_prod',
    short_id: 'spotify_1m',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 1m',
    name_ar: 'Spotify Premium (شهر كامل)',
    button_title: '🎵 Spotify (شهر واحد) — $1.99 ⚡',
    icon_symbol: '🎵',
    market_price: 11.99,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 7.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['استماع بدون إعلانات نهائياً وبأعلى جودة صوتية 320kbps', 'تحميل الأغاني والبودكاست للاستماع في وضع عدم الاتصال Offline', 'تخطي غير محدود للأغاني والتشغيل في الخلفية', 'تفعيل على حسابك الشخصي مع ضمان فوري 100%'],
  },
  {
    id: 'spotify_3m_prod',
    short_id: 'spotify_3m',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 3m',
    name_ar: 'Spotify Premium (3 شهور)',
    button_title: '🎵 Spotify (3 شهور) — $4.99 ⚡',
    icon_symbol: '🎵',
    market_price: 35.99,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['3 شهور من الموسيقى غير المحدودة بدون فواصل', 'مزامنة فورية بين الهاتف، الكمبيوتر، والشاشات الذكية', 'ضمان استبدال رسمي 100% طوال 3 شهور'],
  },
  {
    id: 'spotify_6m_prod',
    short_id: 'spotify_6m',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 6m',
    name_ar: 'Spotify Premium (6 شهور)',
    button_title: '🎵 Spotify (6 شهور) — $8.99 ⚡',
    icon_symbol: '🎵',
    market_price: 71.99,
    our_price: 8.99,
    price_egp: 450,
    price_sar: 34,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['نصف سنة من الاستماع الفائق مع الحفاظ على كافة قوائم التشغيل', 'ضمان استبدال رسمي 100% طوال المدة'],
  },
  {
    id: 'spotify_12m_prod',
    short_id: 'spotify_12m',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 12m',
    name_ar: 'Spotify Premium (سنة كاملة)',
    button_title: '🎵 Spotify (سنة كاملة) — $14.99 ⚡',
    icon_symbol: '🎵',
    market_price: 143.99,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عام كامل من الموسيقى والبودكاست بدون إعلانات وبأعلى جودة', 'تفعيل آمن ورسمي مع ضمان استبدال سنوي 100%'],
  },

  // ── 22. YOUTUBE PREMIUM ──
  {
    id: 'youtube_1m_prod',
    short_id: 'youtube_1m',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 1m',
    name_ar: 'YouTube Premium (شهر كامل)',
    button_title: '▶️ YouTube Premium (شهر واحد) — $1.99 ⚡',
    icon_symbol: '▶️',
    market_price: 13.99,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 7.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['مشاهدة خالية تماماً من الإعلانات على جميع أجهزتك', 'يشمل اشتراك YouTube Music Premium مجاناً', 'تشغيل الفيديوهات والموسيقى في الخلفية وقفل الشاشة', 'تفعيل رسمي وآمن على إيميلك وحسابك الشخصي'],
  },
  {
    id: 'youtube_3m_prod',
    short_id: 'youtube_3m',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 3m',
    name_ar: 'YouTube Premium (3 شهور)',
    button_title: '▶️ YouTube Premium (3 شهور) — $4.99 ⚡',
    icon_symbol: '▶️',
    market_price: 41.99,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['3 شهور من المشاهدة الممتعة بدون إعلانات نهائياً', 'تحميل الفيديوهات بجودة عالية للمشاهدة بدون إنترنت', 'ضمان استبدال رسمي 100% طوال المدة'],
  },
  {
    id: 'youtube_6m_prod',
    short_id: 'youtube_6m',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 6m',
    name_ar: 'YouTube Premium (6 شهور)',
    button_title: '▶️ YouTube Premium (6 شهور) — $8.99 ⚡',
    icon_symbol: '▶️',
    market_price: 83.99,
    our_price: 8.99,
    price_egp: 450,
    price_sar: 34,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['نصف سنة من الاستمتاع بيوتيوب بريميوم ويوتيوب ميوزك', 'ثبات رسمي واستقرار فائق مع ضمان استبدال 100%'],
  },
  {
    id: 'youtube_12m_prod',
    short_id: 'youtube_12m',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 12m',
    name_ar: 'YouTube Premium (سنة كاملة)',
    button_title: '▶️ YouTube Premium (سنة كاملة) — $15.99 ⚡',
    icon_symbol: '▶️',
    market_price: 167.99,
    our_price: 15.99,
    price_egp: 800,
    price_sar: 60,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عام كامل من المشاهدة والاستماع بدون إعلانات', 'توفير يتجاوز 90% مع تفعيل على حسابك الشخصي', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 23. DISNEY+ PREMIUM ──
  {
    id: 'disney_1m_prod',
    short_id: 'disney_1m',
    brand_id: 'disney',
    category_id: 'stream',
    name: 'Disney+ Premium 1m',
    name_ar: 'Disney+ Premium (شهر كامل)',
    button_title: '⭐ Disney+ (شهر واحد) — $2.49 ⚡',
    icon_symbol: '⭐',
    market_price: 13.99,
    our_price: 2.49,
    price_egp: 125,
    price_sar: 9,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['بث بدقة 4K UHD مع مكتبة ديزني ومارفل وStar Wars و National Geographic', 'دبلجة وترجمة عربية كاملة لجميع الأعمال', 'ضمان استبدال رسمي 100%'],
  },
  {
    id: 'disney_12m_prod',
    short_id: 'disney_12m',
    brand_id: 'disney',
    category_id: 'stream',
    name: 'Disney+ Premium 12m',
    name_ar: 'Disney+ Premium (سنة كاملة)',
    button_title: '⭐ Disney+ (سنة كاملة) — $19.99 ⚡',
    icon_symbol: '⭐',
    market_price: 139.99,
    our_price: 19.99,
    price_egp: 1000,
    price_sar: 75,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عام كامل من المتعة العائلية بأفلام ومسلسلات ديزني العالمية', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 24. SHAHID VIP SPORTS ──
  {
    id: 'shahid_1m_prod',
    short_id: 'shahid_1m',
    brand_id: 'shahid',
    category_id: 'stream',
    name: 'Shahid VIP Sports 1m',
    name_ar: 'Shahid VIP شامل الرياضة (شهر كامل)',
    button_title: '🍿 Shahid VIP رياضة (شهر) — $3.99 ⚡',
    icon_symbol: '🍿',
    market_price: 16.99,
    our_price: 3.99,
    price_egp: 200,
    price_sar: 15,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['بث مباشر للدوري السعودي والبطولات الرياضية العالمية وقنوات SSC بدقة FHD', 'مسلسلات وأفلام شاهد الأصلية الحصرية قبل العرض على التلفزيون وبدون فواصل', 'ضمان استبدال فوري 100%'],
  },
  {
    id: 'shahid_12m_prod',
    short_id: 'shahid_12m',
    brand_id: 'shahid',
    category_id: 'stream',
    name: 'Shahid VIP Sports 12m',
    name_ar: 'Shahid VIP شامل الرياضة (سنة كاملة)',
    button_title: '🍿 Shahid VIP رياضة (سنة) — $29.99 ⚡',
    icon_symbol: '🍿',
    market_price: 149.99,
    our_price: 29.99,
    price_egp: 1500,
    price_sar: 112,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['موسم رياضي كامل وترفيه عربي شامل بدون انقطاع', 'توفير يتجاوز 80% مع ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 25. DISCORD NITRO ──
  {
    id: 'discord_1m_prod',
    short_id: 'discord_1m',
    brand_id: 'discord',
    category_id: 'stream',
    name: 'Discord Nitro Boost 1m',
    name_ar: 'Discord Nitro + 2 Server Boosts (شهر كامل)',
    button_title: '🎮 Discord Nitro (شهر واحد) — $2.99 ⚡',
    icon_symbol: '🎮',
    market_price: 9.99,
    our_price: 2.99,
    price_egp: 150,
    price_sar: 11,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['2 سيرفر بوست مجاناً + خصم 30% على أي بوستات إضافية', 'استخدام الإيموجيات والستيكرات المتحركة في أي سيرفر', 'بث الشاشة بجودة فائقة 4K 60fps ورفع ملفات حتى 500MB', 'شارات VIP مميزة وبروفايلات مخصصة لكل سيرفر'],
  },
  {
    id: 'discord_12m_prod',
    short_id: 'discord_12m',
    brand_id: 'discord',
    category_id: 'stream',
    name: 'Discord Nitro Boost 12m',
    name_ar: 'Discord Nitro + 2 Server Boosts (سنة كاملة)',
    button_title: '🎮 Discord Nitro (سنة كاملة) — $24.99 ⚡',
    icon_symbol: '🎮',
    market_price: 99.99,
    our_price: 24.99,
    price_egp: 1250,
    price_sar: 94,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل على حسابك بدون انقطاع', 'ضمان استبدال سنوي شامل 100%'],
  },

  // ── 26. TELEGRAM PREMIUM ──
  {
    id: 'tgprem_3m_prod',
    short_id: 'tgprem_3m',
    brand_id: 'tgprem',
    category_id: 'stream',
    name: 'Telegram Premium 3m',
    name_ar: 'Telegram Premium (3 شهور)',
    button_title: '✈️ Telegram Premium (3 شهور) — $5.99 ⚡',
    icon_symbol: '✈️',
    market_price: 14.99,
    our_price: 5.99,
    price_egp: 300,
    price_sar: 22,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['تفعيل رسمي عبر اسم المستخدم @username بدون الحاجة لكلمة المرور', 'رفع ملفات حتى 4GB وسرعة تنزيل فائقة غير محدودة', 'تحويل الرسائل الصوتية لنصوص مكتوبة لحظياً وترجمة فورية للشات', 'شارة النجمة المميزة والرموز التعبيرية الحصرية'],
  },
  {
    id: 'tgprem_6m_prod',
    short_id: 'tgprem_6m',
    brand_id: 'tgprem',
    category_id: 'stream',
    name: 'Telegram Premium 6m',
    name_ar: 'Telegram Premium (6 شهور)',
    button_title: '✈️ Telegram Premium (6 شهور) — $9.99 ⚡',
    icon_symbol: '✈️',
    market_price: 29.99,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['نصف سنة من مميزات تيليجرام بريميوم الرسمية', 'تفعيل هدية رسمي ومباشر مع ضمان 100%'],
  },
  {
    id: 'tgprem_12m_prod',
    short_id: 'tgprem_12m',
    brand_id: 'tgprem',
    category_id: 'stream',
    name: 'Telegram Premium 12m',
    name_ar: 'Telegram Premium (سنة كاملة)',
    button_title: '✈️ Telegram Premium (سنة كاملة) — $16.99 ⚡',
    icon_symbol: '✈️',
    market_price: 49.99,
    our_price: 16.99,
    price_egp: 850,
    price_sar: 64,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عام كامل من تيليجرام بريميوم الرسمي على يوزرك', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 27. NORDVPN ──
  {
    id: 'nordvpn_12m_prod',
    short_id: 'nordvpn_12m',
    brand_id: 'nordvpn',
    category_id: 'vpn',
    name: 'NordVPN Plus 12m',
    name_ar: 'NordVPN Plus (سنة كاملة)',
    button_title: '🛡️ NordVPN (سنة كاملة) — $6.99 ⚡',
    icon_symbol: '🛡️',
    market_price: 69.99,
    our_price: 6.99,
    price_egp: 350,
    price_sar: 26,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['أكثر من 6,400 خادم فائق السرعة في 111 دولة حول العالم', 'تخطي الحجب والمواقع المحظورة بسرعات قياسية ببروتوكول NordLynx', 'حماية Threat Protection ضد الإعلانات والبرمجيات الخبيثة', 'يعمل على 10 أجهزة في وقت واحد مع ضمان سنوي 100%'],
  },
  {
    id: 'nordvpn_24m_prod',
    short_id: 'nordvpn_24m',
    brand_id: 'nordvpn',
    category_id: 'vpn',
    name: 'NordVPN Plus 24m',
    name_ar: 'NordVPN Plus (سنتين كاملتين)',
    button_title: '🛡️ NordVPN (سنتين) — $11.99 ⚡',
    icon_symbol: '🛡️',
    market_price: 119.99,
    our_price: 11.99,
    price_egp: 600,
    price_sar: 45,
    subscription_duration: 'سنتين كاملتين (24 شهر)',
    warranty_duration: 'سنتين ضمان استبدال',
    advantages_ar: ['الخطة الأفضل حماية وتوفيراً لسنتين متواصلتين', 'ضمان استبدال رسمي 100% طوال 24 شهراً'],
  },

  // ── 28. EXPRESSVPN ──
  {
    id: 'expressvpn_12m_prod',
    short_id: 'expressvpn_12m',
    brand_id: 'expressvpn',
    category_id: 'vpn',
    name: 'ExpressVPN Ultra 12m',
    name_ar: 'ExpressVPN Ultra (سنة كاملة)',
    button_title: '⚡ ExpressVPN (سنة كاملة) — $9.99 ⚡',
    icon_symbol: '⚡',
    market_price: 99.99,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['أسرع خدمة VPN في العالم ببروتوكول Lightway الحصري', 'خوادم في 105 دولة مع ثبات مطلق للألعاب والبث المباشر', 'تشفير عسكري منيع وسياسة عدم حفظ السجلات TrustedServer', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 29. SURFSHARK VPN ──
  {
    id: 'surfshark_12m_prod',
    short_id: 'surfshark_12m',
    brand_id: 'surfshark',
    category_id: 'vpn',
    name: 'Surfshark One 12m',
    name_ar: 'Surfshark One (سنة كاملة)',
    button_title: '🦈 Surfshark (سنة كاملة) — $5.99 ⚡',
    icon_symbol: '🦈',
    market_price: 59.99,
    our_price: 5.99,
    price_egp: 300,
    price_sar: 22,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['عدد غير محدود من الأجهزة Unlimited Devices في نفس الوقت', 'مضاد الفيروسات وحظر الإعلانات CleanWeb مدمج', 'خوادم في 100 دولة مع سرعات 10Gbps فائقة', 'ضمان استبدال سنوي رسمي 100%'],
  },
  {
    id: 'surfshark_24m_prod',
    short_id: 'surfshark_24m',
    brand_id: 'surfshark',
    category_id: 'vpn',
    name: 'Surfshark One 24m',
    name_ar: 'Surfshark One (سنتين كاملتين)',
    button_title: '🦈 Surfshark (سنتين) — $9.99 ⚡',
    icon_symbol: '🦈',
    market_price: 99.99,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: 'سنتين كاملتين (24 شهر)',
    warranty_duration: 'سنتين ضمان استبدال',
    advantages_ar: ['حماية شاملة لجميع أجهزة العائلة لمدة سنتين', 'ضمان استبدال رسمي 100% طوال المدة'],
  },

  // ── 30. KASPERSKY TOTAL SECURITY ──
  {
    id: 'kaspersky_12m_prod',
    short_id: 'kaspersky_12m',
    brand_id: 'kaspersky',
    category_id: 'vpn',
    name: 'Kaspersky Total Security 12m Key',
    name_ar: 'Kaspersky Total Security (سنة كاملة - مفتاح رقمي)',
    button_title: '🔐 Kaspersky (سنة كاملة) — $4.99 ⚡',
    icon_symbol: '🔐',
    market_price: 49.99,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مفتاح ترخيص رقمي أصلي رسمي يقبل التفعيل على تطبيق كاسبرسكي مباشرة', 'حماية شاملة في الوقت الحقيقي من الفيروسات وبرامج الفدية والتجسس', 'جدار ناري ذكي وحماية المعاملات المصرفية Safe Money', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 31. NOTION AI PLUS ──
  {
    id: 'notion_12m_prod',
    short_id: 'notion_12m',
    brand_id: 'notion',
    category_id: 'prod',
    name: 'Notion AI Plus 12m',
    name_ar: 'Notion AI Plus (سنة كاملة)',
    button_title: '📝 Notion AI (سنة كاملة) — $14.99 ⚡',
    icon_symbol: '📝',
    market_price: 120.00,
    our_price: 14.99,
    price_egp: 750,
    price_sar: 56,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مساعد ذكاء اصطناعي غير محدود لكتابة وتلخيص الملاحظات وإدارة المشاريع', 'بحث دلالي ذكي داخل كافة صفحات وقواعد بيانات Notion', 'رفع ملفات بحجم غير محدود وتاريخ نسخ متقدم', 'ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 32. GRAMMARLY PREMIUM ──
  {
    id: 'grammarly_1m_prod',
    short_id: 'grammarly_1m',
    brand_id: 'grammarly',
    category_id: 'prod',
    name: 'Grammarly Premium 1m',
    name_ar: 'Grammarly Premium (شهر كامل)',
    button_title: '🔤 Grammarly (شهر واحد) — $3.49 ⚡',
    icon_symbol: '🔤',
    market_price: 30.00,
    our_price: 3.49,
    price_egp: 175,
    price_sar: 13,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['تصحيح قواعد اللغة المتقدم وإعادة صياغة الجمل لأسلوب احترافي', 'كاشف الاقتباس والانتحال الأدبي Plagiarism Checker المدمج', 'اقتراحات تحسين النبرة والمفردات مع الذكاء الاصطناعي', 'يعمل مع Word والمتصفح وتطبيقات الجوال والكمبيوتر'],
  },
  {
    id: 'grammarly_12m_prod',
    short_id: 'grammarly_12m',
    brand_id: 'grammarly',
    category_id: 'prod',
    name: 'Grammarly Premium 12m',
    name_ar: 'Grammarly Premium (سنة كاملة)',
    button_title: '🔤 Grammarly (سنة كاملة) — $19.99 ⚡',
    icon_symbol: '🔤',
    market_price: 144.00,
    our_price: 19.99,
    price_egp: 1000,
    price_sar: 75,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['الاشتراك الأفضل للطلاب والباحثين والكتّاب على مدار عام كامل', 'توفير يتجاوز 85% مع ضمان استبدال سنوي رسمي 100%'],
  },

  // ── 33. DUOLINGO SUPER ──
  {
    id: 'duolingo_12m_prod',
    short_id: 'duolingo_12m',
    brand_id: 'duolingo',
    category_id: 'prod',
    name: 'Duolingo Super 12m',
    name_ar: 'Duolingo Super (سنة كاملة)',
    button_title: '📚 Duolingo Super (سنة كاملة) — $7.99 ⚡',
    icon_symbol: '📚',
    market_price: 83.99,
    our_price: 7.99,
    price_egp: 400,
    price_sar: 30,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['قلوب وطاقة غير محدودة Unlimited Hearts للتعلم المستمر دون توقف', 'خالي تماماً من الإعلانات المزعجة', 'مراجعة وتصحيح الأخطاء واختبارات التقدم الشخصية', 'تفعيل على إيميلك الشخصي مع ضمان سنوي 100%'],
  },

  // ── 34. MICROSOFT 365 + 1TB ──
  {
    id: 'm365_12m_prod',
    short_id: 'm365_12m',
    brand_id: 'm365',
    category_id: 'prod',
    name: 'Microsoft 365 12m',
    name_ar: 'Microsoft 365 + 1TB OneDrive (سنة كاملة)',
    button_title: '📊 Microsoft 365 (سنة كاملة) — $4.99 ⚡',
    icon_symbol: '📊',
    market_price: 69.99,
    our_price: 4.99,
    price_egp: 250,
    price_sar: 19,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['كافة تطبيقات أوفيس الأصلية (Word, Excel, PowerPoint, Outlook)', 'مساحة تخزين سحابية ضخمة 1TB على OneDrive', 'تفعيل رسمي على 5 أجهزة (PC, Mac, iPhone, Android)', 'ضمان استبدال سنوي رسمي 100%'],
  },
  {
    id: 'm365_lifetime_prod',
    short_id: 'm365_lifetime',
    brand_id: 'm365',
    category_id: 'prod',
    name: 'Microsoft 365 Lifetime Account',
    name_ar: 'Microsoft 365 + 1TB OneDrive (مدى الحياة)',
    button_title: '📊 Microsoft 365 (مدى الحياة) — $9.99 ⚡',
    icon_symbol: '📊',
    market_price: 199.99,
    our_price: 9.99,
    price_egp: 500,
    price_sar: 37,
    subscription_duration: 'وصول دائم مدى الحياة',
    warranty_duration: 'ضمان رسمي مدى الحياة',
    advantages_ar: ['حساب خاص ومفعل دائم مدى الحياة بدون أي اشتراكات سنوية', '1TB سحابي خاص على OneDrive وحزمة برامج Office 365 كاملة', 'يقبل التثبيت على 5 أجهزة في وقت واحد', 'ضمان استبدال رسمي دائم'],
  },

  // ── 35. WINDOWS RETAIL KEYS ──
  {
    id: 'win11_retail_prod',
    short_id: 'win11_retail',
    brand_id: 'win11',
    category_id: 'prod',
    name: 'Windows 11 Pro Retail Key Lifetime',
    name_ar: 'Windows 11 Pro Retail Key (مفتاح أصلي مدى الحياة)',
    button_title: '🪟 Windows 11 Pro (مدى الحياة) — $4.49 ⚡',
    icon_symbol: '🪟',
    market_price: 199.99,
    our_price: 4.49,
    price_egp: 225,
    price_sar: 17,
    subscription_duration: 'تفعيل دائم مدى الحياة',
    warranty_duration: 'ضمان أصلي مدى الحياة',
    advantages_ar: ['مفتاح ترخيص أصلي Retail مكون من 25 رمزاً يربط بجهازك مباشرة', 'يدعم جميع اللغات ويقبل التحديثات الرسمية من مايكروسوفت مدى الحياة', 'يدعم الفورمات وإعادة التثبيت على نفس الجهاز', 'ضمان تفعيل رسمي فوري 100%'],
  },
  {
    id: 'win10_retail_prod',
    short_id: 'win10_retail',
    brand_id: 'win11',
    category_id: 'prod',
    name: 'Windows 10 Pro Retail Key Lifetime',
    name_ar: 'Windows 10 Pro Retail Key (مفتاح أصلي مدى الحياة)',
    button_title: '🪟 Windows 10 Pro (مدى الحياة) — $3.99 ⚡',
    icon_symbol: '🪟',
    market_price: 199.99,
    our_price: 3.99,
    price_egp: 200,
    price_sar: 15,
    subscription_duration: 'تفعيل دائم مدى الحياة',
    warranty_duration: 'ضمان أصلي مدى الحياة',
    advantages_ar: ['مفتاح ترخيص أصلي Retail دائم مدى الحياة لنظام Windows 10 Pro', 'يقبل الترقية المجانية المباشرة إلى Windows 11 Pro بضغطة زر', 'يقبل التحديثات وإعادة التثبيت', 'ضمان تفعيل رسمي فوري 100%'],
  },
];

export function getCategories() {
  return STORE_CATEGORIES;
}

export function getCategoryById(categoryId: string) {
  return STORE_CATEGORIES.find((c) => c.id === categoryId) || null;
}

export function getBrandsByCategory(categoryId: string) {
  return STORE_BRANDS.filter((b) => b.category_id === categoryId);
}

export function getBrandById(brandId: string) {
  return STORE_BRANDS.find((b) => b.id === brandId) || null;
}

export function getCatalogByBrand(brandId: string) {
  return STORE_CATALOG.filter((p) => p.brand_id === brandId);
}

export function getProductsByBrand(brandId: string) {
  return STORE_CATALOG.filter((p) => p.brand_id === brandId);
}

export function getCatalogByCategory(categoryId: string) {
  return STORE_CATALOG.filter((p) => p.category_id === categoryId);
}

export function getProductById(productId: string) {
  return (
    STORE_CATALOG.find((p) => p.id === productId || p.short_id === productId) ||
    null
  );
}

export function getProductByShortIdOrSlug(identifier: string) {
  if (!identifier) return null;
  const idStr = String(identifier).trim().toLowerCase();
  return (
    STORE_CATALOG.find(
      (p) =>
        (p.id && p.id.toLowerCase() === idStr) ||
        (p.short_id && p.short_id.toLowerCase() === idStr) ||
        (p.name && p.name.toLowerCase() === idStr)
    ) || null
  );
}
