export const STORE_CATEGORIES = [
  { id: 'ai', name_ar: 'الذكاء الاصطناعي (AI)', name_en: 'Artificial Intelligence (AI)', emoji: '🤖' },
  { id: 'dev', name_ar: 'أدوات المطورين والبرمجة', name_en: 'Developer Tools', emoji: '💻' },
  { id: 'design', name_ar: 'التصميم والمونتاج', name_en: 'Design & Creative', emoji: '🎨' },
  { id: 'stream', name_ar: 'الترفيه والموسيقى', name_en: 'Streaming & Media', emoji: '🎬' },
  { id: 'vpn', name_ar: 'الحماية والـ VPN', name_en: 'Security & VPN', emoji: '🔐' },
  { id: 'prod', name_ar: 'الإنتاجية والأوفيس', name_en: 'Productivity & Office', emoji: '📚' },
];

export const STORE_BRANDS = [
  // AI
  { id: 'gemini', category_id: 'ai', name_ar: 'Google Gemini Advanced', name_en: 'Google Gemini Advanced', icon: '✦', desc: 'أحدث نماذج الذكاء الاصطناعي 2TB سحابية' },
  { id: 'chatgpt', category_id: 'ai', name_ar: 'ChatGPT (OpenAI Plus/Pro)', name_en: 'ChatGPT Plus/Pro', icon: '🟢', desc: 'نماذج GPT-4o و OpenAI o1 Pro Mode' },
  { id: 'claude', category_id: 'ai', name_ar: 'Claude AI (Anthropic Pro)', name_en: 'Claude AI Pro', icon: '🟣', desc: 'أقوى نموذج كتابة وتفكير Claude 3.7 Sonnet' },
  { id: 'perplexity', category_id: 'ai', name_ar: 'Perplexity AI Pro', name_en: 'Perplexity AI Pro', icon: '🌌', desc: 'محرك البحث الذكي المتقدم للباحثين' },
  { id: 'midjourney', category_id: 'ai', name_ar: 'Midjourney AI Imaging', name_en: 'Midjourney AI', icon: '🌟', desc: 'أعلى دقة لتوليد الصور والتصاميم الفنية' },
  { id: 'elevenlabs', category_id: 'ai', name_ar: 'ElevenLabs AI Voice', name_en: 'ElevenLabs Voice AI', icon: '🎙️', desc: 'توليد أصوات بشرية ودبلجة واقعية فوري' },
  { id: 'grok', category_id: 'ai', name_ar: 'Grok 2 / SuperGrok', name_en: 'Grok 2 SuperGrok', icon: '⚡', desc: 'ذكاء إيلون ماسك المباشر مع بيانات X' },
  { id: 'runway', category_id: 'ai', name_ar: 'Runway Gen-3 Video AI', name_en: 'Runway Gen-3 Video', icon: '🎬', desc: 'صناعة ومونتاج الفيديو بالذكاء الاصطناعي' },

  // DEV
  { id: 'cursor', category_id: 'dev', name_ar: 'Cursor AI (Pro & Ultra)', name_en: 'Cursor AI Pro & Ultra', icon: '💻', desc: 'محرر الأكواد الذكي الأقوى للمطورين' },
  { id: 'copilot', category_id: 'dev', name_ar: 'GitHub Copilot', name_en: 'GitHub Copilot', icon: '🐙', desc: 'مساعد البرمجة الذكي داخل VS Code' },
  { id: 'v0dev', category_id: 'dev', name_ar: 'v0.dev / Bolt.new Pro', name_en: 'v0.dev / Bolt.new Pro', icon: '⚡', desc: 'بناء واجهات وتطبيقات الويب بالـ AI' },
  { id: 'jetbrains', category_id: 'dev', name_ar: 'JetBrains All Products', name_en: 'JetBrains All Products', icon: '📦', desc: 'كل برامج جيت برينز (WebStorm, PyCharm)' },
  { id: 'replit', category_id: 'dev', name_ar: 'Replit Core & Agent Pro', name_en: 'Replit Core & Agent', icon: '🔥', desc: 'بيئة تطوير سحابية وبناء مشاريع فوري' },

  // DESIGN
  { id: 'canva', category_id: 'design', name_ar: 'Canva Pro', name_en: 'Canva Pro', icon: '🎨', desc: 'قوالب وتصاميم ومؤثرات غير محدودة' },
  { id: 'capcut', category_id: 'design', name_ar: 'CapCut Pro (4K)', name_en: 'CapCut Pro 4K', icon: '✂️', desc: 'تصدير بدون علامة مائية وفلاتر برو' },
  { id: 'adobe', category_id: 'design', name_ar: 'Adobe Creative Cloud All Apps', name_en: 'Adobe Creative Cloud', icon: '🟥', desc: '20+ تطبيق أدوبي كاملة (Photoshop, Premiere)' },
  { id: 'figma', category_id: 'design', name_ar: 'Figma Professional', name_en: 'Figma Professional', icon: '🖌️', desc: 'تصميم واجهات وتجربة المستخدم للفرق' },
  { id: 'freepik', category_id: 'design', name_ar: 'Freepik Premium', name_en: 'Freepik Premium', icon: '📸', desc: 'ملايين الصور والملفات الفيكتور الحصرية' },
  { id: 'envato', category_id: 'design', name_ar: 'Envato Elements', name_en: 'Envato Elements', icon: '🎬', desc: 'تحميل غير محدود للقوالب والأكواد والموسيقى' },

  // STREAMING
  { id: 'netflix', category_id: 'stream', name_ar: 'Netflix 4K UHD Ultra', name_en: 'Netflix 4K UHD Ultra', icon: '🎬', desc: 'أعلى جودة 4K مع صوت ثلاثي الأبعاد وPIN' },
  { id: 'spotify', category_id: 'stream', name_ar: 'Spotify Premium', name_en: 'Spotify Premium', icon: '🎵', desc: 'استماع بدون إعلانات وتحميل أوفلاين' },
  { id: 'youtube', category_id: 'stream', name_ar: 'YouTube Premium + Music', name_en: 'YouTube Premium', icon: '▶️', desc: 'مشاهدة بدون إعلانات وتشغيل بالخلفية' },
  { id: 'disney', category_id: 'stream', name_ar: 'Disney+ Premium', name_en: 'Disney+ Premium', icon: '⭐', desc: 'أفلام ومسلسلات ديزني ومارفل بدقة 4K' },
  { id: 'shahid', category_id: 'stream', name_ar: 'Shahid VIP', name_en: 'Shahid VIP', icon: '🍿', desc: 'مباريات حصرية ومسلسلات بدون فواصل' },
  { id: 'discord', category_id: 'stream', name_ar: 'Discord Nitro Boost', name_en: 'Discord Nitro Boost', icon: '🎮', desc: 'إيموجي متحركة وسيرفر بوست ومميزات VIP' },
  { id: 'tgprem', category_id: 'stream', name_ar: 'Telegram Premium', name_en: 'Telegram Premium', icon: '✈️', desc: 'سرعة تنزيل مضاعفة وشارات مميزة و4GB رفع' },

  // VPN & SECURITY
  { id: 'nordvpn', category_id: 'vpn', name_ar: 'NordVPN Plus', name_en: 'NordVPN Plus', icon: '🛡️', desc: 'حماية وتشفير وتخطي الحجب بسرعات فائقة' },
  { id: 'expressvpn', category_id: 'vpn', name_ar: 'ExpressVPN Ultra', name_en: 'ExpressVPN Ultra', icon: '⚡', desc: 'أسرع VPN عالمي مع خوادم في 105 دولة' },
  { id: 'surfshark', category_id: 'vpn', name_ar: 'Surfshark One', name_en: 'Surfshark One', icon: '🦈', desc: 'أجهزة غير محدودة مع حماية كاملة ومضاد فيروسات' },
  { id: 'kaspersky', category_id: 'vpn', name_ar: 'Kaspersky Total Security', name_en: 'Kaspersky Total Security', icon: '🔐', desc: 'حماية شاملة من الفيروسات والبرمجيات الخبيثة' },

  // PRODUCTIVITY & OFFICE
  { id: 'notion', category_id: 'prod', name_ar: 'Notion AI Plus', name_en: 'Notion AI Plus', icon: '📝', desc: 'تنظيم المهام والملاحظات مع ذكاء غير محدود' },
  { id: 'grammarly', category_id: 'prod', name_ar: 'Grammarly Premium', name_en: 'Grammarly Premium', icon: '🔤', desc: 'تدقيق لغوي وصياغة احترافية بالذكاء الاصطناعي' },
  { id: 'duolingo', category_id: 'prod', name_ar: 'Duolingo Super', name_en: 'Duolingo Super', icon: '📚', desc: 'تعلم اللغات بقلوب غير محدودة وبدون إعلانات' },
  { id: 'm365', category_id: 'prod', name_ar: 'Microsoft 365 + 1TB', name_en: 'Microsoft 365 + 1TB', icon: '📊', desc: 'Word, Excel, PowerPoint مع 1TB سحابي' },
  { id: 'win11', category_id: 'prod', name_ar: 'Windows 11 Pro Retail', name_en: 'Windows 11 Pro Retail Key', icon: '🪟', desc: 'مفتاح تفعيل أصلي دائم مدى الحياة' },
];

export const STORE_CATALOG = [
  // ── 1. GOOGLE GEMINI ──
  {
    id: 'gemini_1m_prod',
    short_id: 'gemini_1m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 1m',
    name_ar: 'Google Gemini Advanced (شهر كامل)',
    button_title: '✦ Gemini (1 شهر) — $0.19 🔥',
    icon_symbol: '✦',
    market_price: 19.99,
    our_price: 0.19,
    price_egp: 10,
    price_sar: 0.8,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أحدث نماذج Gemini 3.7 Flash و 2.5 Pro', 'مساحة تخزين سحابية 2TB على Google One', 'ضمان استبدال فوري 100% طوال المدة'],
  },
  {
    id: 'gemini_3m_prod',
    short_id: 'gemini_3m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 3m',
    name_ar: 'Google Gemini Advanced (3 شهور)',
    button_title: '✦ Gemini (3 شهور) — $0.29 🔥',
    icon_symbol: '✦',
    market_price: 59.99,
    our_price: 0.29,
    price_egp: 15,
    price_sar: 1.2,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['أحدث نماذج Gemini المتقدمة للبرمجة والتفكير', 'مساحة تخزين 2TB Google One سحابية', 'ضمان استبدال ذهبي طوال 3 شهور'],
  },
  {
    id: 'gemini_6m_prod',
    short_id: 'gemini_6m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 6m',
    name_ar: 'Google Gemini Advanced (6 شهور)',
    button_title: '✦ Gemini (6 شهور) — $0.39 🔥',
    icon_symbol: '✦',
    market_price: 119.99,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['وصول فائق السرعة لنماذج الذكاء الاصطناعي', 'سعة 2TB سحابية على Google Drive', 'ضمان كامل طوال نصف سنة'],
  },
  {
    id: 'gemini_12m_prod',
    short_id: 'gemini_12m',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 12m',
    name_ar: 'Google Gemini Advanced (سنة كاملة)',
    button_title: '✦ Gemini (سنة كاملة) — $0.49 🔥',
    icon_symbol: '✦',
    market_price: 239.99,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل مدعوم بـ Antigravity', '2 تيرابايت تخزين Google One أصلي', 'ضمان استبدال سنوي شامل 100%'],
  },
  {
    id: '643361f7-7475-48ee-af69-20bf655da73a',
    short_id: '643361f7',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Advanced 18m VIP',
    name_ar: 'Google Gemini Advanced (18 شهر VIP)',
    button_title: '✦ Gemini (18 شهر VIP) — $0.59 🔥',
    icon_symbol: '✦',
    market_price: 350.00,
    our_price: 0.59,
    price_egp: 30,
    price_sar: 2.5,
    subscription_duration: '18 شهراً كاملاً',
    warranty_duration: '18 شهراً ضمان ذهبي',
    advantages_ar: ['وصول لأحدث نماذج Gemini 3.7 و 2.5 Pro للبرمجة', 'سعة تخزين ضخمة 2TB سحابية Google One', 'دعم فني خاص وضمان استبدال كامل 18 شهراً'],
  },
  {
    id: 'gemini_team_prod',
    short_id: 'gemini_team',
    brand_id: 'gemini',
    category_id: 'ai',
    name: 'Gemini Team Workspace',
    name_ar: 'Gemini Workspace Team (باقة الفريق)',
    button_title: '✦ Gemini Team Workspace — $0.99 🔥',
    icon_symbol: '✦',
    market_price: 360.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مساحة عمل مشتركة للفريق مع صلاحيات متقدمة', 'أمان وخصوصية بيانات المؤسسات Enterprise', 'ضمان رسمي ودعم كامل طوال السنة'],
  },

  // ── 2. CHATGPT / OPENAI ──
  {
    id: 'b2c3d4e5-1111-4444-8888-000000000003',
    short_id: 'b2c3d4e5',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 1m',
    name_ar: 'ChatGPT Plus (شهر كامل)',
    button_title: '🟢 ChatGPT Plus (شهر) — $0.49 🔥',
    icon_symbol: '🟢',
    market_price: 20.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['الوصول الكامل لنماذج GPT-4o ونموذج التفكير OpenAI o1', 'توليد الصور بدقة فائقة عبر DALL-E 3 داخل المحادثة', 'الوضع الصوتي المتقدم Advanced Voice Mode'],
  },
  {
    id: 'chatgpt_plus_3m_prod',
    short_id: 'chatgpt_3m',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 3m',
    name_ar: 'ChatGPT Plus (3 شهور)',
    button_title: '🟢 ChatGPT Plus (3 شهور) — $0.99 🔥',
    icon_symbol: '🟢',
    market_price: 60.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['وصول دائم بدون انقطاع لنماذج GPT-4o و o1', 'تحليل البيانات المتقدم ورفع الملفات الكبيرة', 'ضمان استبدال فوري طوال 3 شهور'],
  },
  {
    id: 'chatgpt_plus_6m_prod',
    short_id: 'chatgpt_6m',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 6m',
    name_ar: 'ChatGPT Plus (6 شهور)',
    button_title: '🟢 ChatGPT Plus (6 شهور) — $1.49 🔥',
    icon_symbol: '🟢',
    market_price: 120.00,
    our_price: 1.49,
    price_egp: 75,
    price_sar: 6.0,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['استخدام غير محدود للمساعدات الذكية GPTs المخصصة', 'توليد صور متقدم وسرعة استجابة فائقة', 'ضمان كامل طوال الـ 6 شهور'],
  },
  {
    id: 'chatgpt_plus_1y_prod',
    short_id: 'chatgpt_1y',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Plus 1y',
    name_ar: 'ChatGPT Plus (سنة كاملة)',
    button_title: '🟢 ChatGPT Plus (سنة) — $1.99 🔥',
    icon_symbol: '🟢',
    market_price: 240.00,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 8.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي رسمي خاص ومستقل', 'أولوية قصوى عند إطلاق أي نماذج جديدة من OpenAI', 'ضمان ذهبي للاستبدال والدعم 100%'],
  },
  {
    id: 'b2c3d4e5-2222-4444-8888-000000000004',
    short_id: 'chatgpt_pro',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Pro Ultra',
    name_ar: 'ChatGPT Pro Ultra (شهر)',
    button_title: '🚀 ChatGPT Pro Ultra — $2.49 🔥',
    icon_symbol: '🚀',
    market_price: 200.00,
    our_price: 2.49,
    price_egp: 125,
    price_sar: 9.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['وصول حصري لنموذج o1 Pro Mode لأعلى دقة تفكير عالمياً', 'استخدام غير محدود نهائياً لرسائل نموذج GPT-4o', 'أقصى طاقة حوسبية من OpenAI'],
  },
  {
    id: 'chatgpt_team_prod',
    short_id: 'chatgpt_team',
    brand_id: 'chatgpt',
    category_id: 'ai',
    name: 'ChatGPT Team Workspace',
    name_ar: 'ChatGPT Team Workspace (سنة)',
    button_title: '🏢 ChatGPT Team Workspace — $1.79 🔥',
    icon_symbol: '🏢',
    market_price: 300.00,
    our_price: 1.79,
    price_egp: 90,
    price_sar: 7.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['حدود رسائل أعلى بكثير من البلس العادي', 'مساحة عمل مخصصة ولا يتم تدريب النماذج على بياناتك', 'ضمان استبدال سنوي شامل'],
  },

  // ── 3. CLAUDE AI ──
  {
    id: 'claude_1m_prod',
    short_id: 'claude_1m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 1m',
    name_ar: 'Claude Pro (شهر كامل)',
    button_title: '🟣 Claude Pro (شهر) — $0.49 🔥',
    icon_symbol: '🟣',
    market_price: 20.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['وصول كامل لنموذج Claude 3.7 Sonnet الرائد برمجياً', 'ميزة Claude Artifacts للتفاعل المباشر مع الكود والواجهات', 'أعلى دقة في الكتابة والتحليل الأدبي والتقني'],
  },
  {
    id: 'claude_3m_prod',
    short_id: 'claude_3m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 3m',
    name_ar: 'Claude Pro (3 شهور)',
    button_title: '🟣 Claude Pro (3 شهور) — $0.99 🔥',
    icon_symbol: '🟣',
    market_price: 60.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['استخدام مكثف بـ 5 أضعاف مقارنة بالحساب المجاني', 'نافذة سياق ضخمة حتى 200k tokens لقراءة الكتب والملفات', 'ضمان كامل طوال الـ 3 شهور'],
  },
  {
    id: 'claude_6m_prod',
    short_id: 'claude_6m',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Pro 6m',
    name_ar: 'Claude Pro (6 شهور)',
    button_title: '🟣 Claude Pro (6 شهور) — $1.49 🔥',
    icon_symbol: '🟣',
    market_price: 120.00,
    our_price: 1.49,
    price_egp: 75,
    price_sar: 6.0,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['أولوية في أوقات الذروة وتشغيل فوري', 'دعم متقدم للمشاريع البرمجية الضخمة', 'ضمان استبدال نصف سنوي'],
  },
  {
    id: 'claude_team_prod',
    short_id: 'claude_team',
    brand_id: 'claude',
    category_id: 'ai',
    name: 'Claude Team Workspace',
    name_ar: 'Claude Team Workspace (سنة)',
    button_title: '🏢 Claude Team Workspace — $1.99 🔥',
    icon_symbol: '🏢',
    market_price: 360.00,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 8.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مساحة عمل للفرق مع أعلى حدود استهلاك', 'إدارة مستندات مشتركة وتحليلات متقدمة', 'ضمان ذهبي سنوي شامل'],
  },

  // ── 4. PERPLEXITY AI ──
  {
    id: 'perplexity_1m_prod',
    short_id: 'perp_1m',
    brand_id: 'perplexity',
    category_id: 'ai',
    name: 'Perplexity Pro 1m',
    name_ar: 'Perplexity AI Pro (شهر)',
    button_title: '🌌 Perplexity Pro (شهر) — $0.39 🔥',
    icon_symbol: '🌌',
    market_price: 20.00,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أكثر من 300+ بحث Pro يومياً مع مصادر موثقة لحظياً', 'إمكانية التبديل بين Claude 3.7 و GPT-4o و Sonar', 'رفع ملفات وصور غير محدود للتحليل الأكاديمي'],
  },
  {
    id: 'perplexity_1y_prod',
    short_id: 'perp_1y',
    brand_id: 'perplexity',
    category_id: 'ai',
    name: 'Perplexity Pro 1y',
    name_ar: 'Perplexity AI Pro (سنة كاملة)',
    button_title: '🌌 Perplexity Pro (سنة) — $0.89 🔥',
    icon_symbol: '🌌',
    market_price: 200.00,
    our_price: 0.89,
    price_egp: 45,
    price_sar: 3.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل للباحثين والطلاب والمهندسين', 'توليد إجابات دقيقة مع مراجع ومصادر ومخططات بيانية', 'ضمان استبدال سنوي 100%'],
  },

  // ── 5. MIDJOURNEY ──
  {
    id: 'midjourney_std_prod',
    short_id: 'mj_std',
    brand_id: 'midjourney',
    category_id: 'ai',
    name: 'Midjourney Standard 1m',
    name_ar: 'Midjourney Standard (شهر)',
    button_title: '🌟 Midjourney Standard — $0.49 🔥',
    icon_symbol: '🌟',
    market_price: 30.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['15 ساعة توليد سريع Fast GPU شهرياً', 'توليد غير محدود في وضع Relax Mode', 'حقوق استخدام تجاري كاملة للصور المُنشأة'],
  },
  {
    id: 'midjourney_pro_prod',
    short_id: 'mj_pro',
    brand_id: 'midjourney',
    category_id: 'ai',
    name: 'Midjourney Pro 1m',
    name_ar: 'Midjourney Pro Plan (شهر)',
    button_title: '🌟 Midjourney Pro — $0.99 🔥',
    icon_symbol: '🌟',
    market_price: 60.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['30 ساعة توليد سريع Fast GPU', 'ميزة وضع التخفي Stealth Mode لإخفاء صورك من العامة', 'ضمان استبدال فوري طوال الشهر'],
  },

  // ── 6. ELEVENLABS & GROK & RUNWAY ──
  {
    id: 'elevenlabs_creator_prod',
    short_id: 'eleven_crt',
    brand_id: 'elevenlabs',
    category_id: 'ai',
    name: 'ElevenLabs Creator 1m',
    name_ar: 'ElevenLabs Creator (شهر)',
    button_title: '🎙️ ElevenLabs Creator — $0.45 🔥',
    icon_symbol: '🎙️',
    market_price: 22.00,
    our_price: 0.45,
    price_egp: 22,
    price_sar: 1.8,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['100,000 حرف شهرياً لتوليد الصوت البشري الواقعي', 'استنساخ الأصوات الصوتية Voice Cloning بدقة خيالية', 'دعم اللغة العربية بأعلى فصاحة ومشاعر'],
  },
  {
    id: 'elevenlabs_pro_prod',
    short_id: 'eleven_pro',
    brand_id: 'elevenlabs',
    category_id: 'ai',
    name: 'ElevenLabs Pro 1m',
    name_ar: 'ElevenLabs Pro (شهر)',
    button_title: '🎙️ ElevenLabs Pro — $0.89 🔥',
    icon_symbol: '🎙️',
    market_price: 99.00,
    our_price: 0.89,
    price_egp: 45,
    price_sar: 3.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['500,000 حرف شهرياً واستنساخ احترافي فائق الجودة', 'دبلجة تلقائية لمقاطع الفيديو بلغات متعددة', 'ضمان استبدال فوري كامل'],
  },
  {
    id: 'grok_1m_prod',
    short_id: 'grok_1m',
    brand_id: 'grok',
    category_id: 'ai',
    name: 'Grok 2 SuperGrok 1m',
    name_ar: 'SuperGrok 2 (شهر كامل)',
    button_title: '⚡ SuperGrok 2 (شهر) — $0.39 🔥',
    icon_symbol: '⚡',
    market_price: 16.00,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['توليد صور واقعية فائقة وبدون قيود عبر Flux', 'معلومات حية ولحظية مرتبطة بمنصة X مباشرة', 'ضمان كامل طوال مدة الشهر'],
  },
  {
    id: 'grok_1y_prod',
    short_id: 'grok_1y',
    brand_id: 'grok',
    category_id: 'ai',
    name: 'Grok 2 SuperGrok 1y',
    name_ar: 'SuperGrok 2 (سنة كاملة)',
    button_title: '⚡ SuperGrok 2 (سنة) — $0.99 🔥',
    icon_symbol: '⚡',
    market_price: 160.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل غير محدود', 'توليد نصوص وتحليل وسائط ورسوم بيانية', 'ضمان سنوي شامل 100%'],
  },
  {
    id: 'runway_1m_prod',
    short_id: 'runway_1m',
    brand_id: 'runway',
    category_id: 'ai',
    name: 'Runway Gen-3 Unlimited 1m',
    name_ar: 'Runway Gen-3 Alpha (شهر)',
    button_title: '🎬 Runway Unlimited — $0.69 🔥',
    icon_symbol: '🎬',
    market_price: 35.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['توليد فيديو سينمائي بدقة عالية عبر Gen-3 Alpha', 'تعديل الفيديوهات ومسح العناصر بالذكاء الاصطناعي', 'ضمان فوري طوال الشهر'],
  },

  // ── 7. CURSOR AI ──
  {
    id: 'd4e5f6a7-1111-4444-8888-000000000007',
    short_id: 'cursor_pro',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 1m',
    name_ar: 'Cursor AI Pro (شهر كامل)',
    button_title: '💻 Cursor Pro (شهر) — $0.49 🔥',
    icon_symbol: '💻',
    market_price: 20.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['500 طلب سريع Fast Requests شهرياً بنماذج Claude 3.7 و GPT-4o', 'إكمال تلقائي ذكي غير محدود لكتابة وتوقع الأكواد', 'تفعيل رسمي مضمون كامل المدة'],
  },
  {
    id: 'cursor_3m_prod',
    short_id: 'cursor_3m',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 3m',
    name_ar: 'Cursor AI Pro (3 شهور)',
    button_title: '💻 Cursor Pro (3 شهور) — $0.99 🔥',
    icon_symbol: '💻',
    market_price: 60.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['استخدام يومي مكثف للمطورين وبناء المشاريع', 'تعديل ملفات متعددة بنقرة واحدة Composer Multi-file', 'ضمان استبدال طوال 3 شهور'],
  },
  {
    id: 'cursor_6m_prod',
    short_id: 'cursor_6m',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 6m',
    name_ar: 'Cursor AI Pro (6 شهور)',
    button_title: '💻 Cursor Pro (6 شهور) — $1.49 🔥',
    icon_symbol: '💻',
    market_price: 120.00,
    our_price: 1.49,
    price_egp: 75,
    price_sar: 6.0,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['أعلى إنتاجية للمبرمجين مع ميزة Terminal Debugging التلقائي', 'فحص أخطاء الأكواد وحلها لحظياً', 'ضمان استبدال كامل نصف سنوي'],
  },
  {
    id: 'cursor_1y_prod',
    short_id: 'cursor_1y',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor AI Pro 1y',
    name_ar: 'Cursor AI Pro (سنة كاملة)',
    button_title: '💻 Cursor Pro (سنة) — $1.99 🔥',
    icon_symbol: '💻',
    market_price: 240.00,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 8.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل ومستقر بدون أي انقطاع', 'تحديثات مستمرة لأحدث نماذج الذكاء الاصطناعي', 'ضمان ذهبي شامل 100% طوال السنة'],
  },
  {
    id: 'cursor_ultra_prod',
    short_id: 'cursor_ultra',
    brand_id: 'cursor',
    category_id: 'dev',
    name: 'Cursor Ultra Business',
    name_ar: 'Cursor Ultra Enterprise (شهر)',
    button_title: '🚀 Cursor Ultra Business — $2.99 🔥',
    icon_symbol: '🚀',
    market_price: 200.00,
    our_price: 2.99,
    price_egp: 150,
    price_sar: 12.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['طلبات سريعة غير محدودة وأولوية قصوى على الخوادم', 'أمان مؤسسات مع دعم فني VIP مباشر للمطورين', 'ضمان فوري 100%'],
  },

  // ── 8. GITHUB COPILOT & DEV SUITE ──
  {
    id: 'copilot_1m_prod',
    short_id: 'copilot_1m',
    brand_id: 'copilot',
    category_id: 'dev',
    name: 'GitHub Copilot 1m',
    name_ar: 'GitHub Copilot Individual (شهر)',
    button_title: '🐙 Copilot (شهر) — $0.39 🔥',
    icon_symbol: '🐙',
    market_price: 10.00,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['مساعد الكود الرسمي في VS Code و JetBrains و Neovim', 'توقع الأكواد وكتابة الدوال التلقائية وشرح الأخطاء', 'تفعيل على حسابك أو حساب جاهز مع الضمان'],
  },
  {
    id: 'copilot_1y_prod',
    short_id: 'copilot_1y',
    brand_id: 'copilot',
    category_id: 'dev',
    name: 'GitHub Copilot 1y',
    name_ar: 'GitHub Copilot Individual (سنة)',
    button_title: '🐙 Copilot (سنة كاملة) — $0.89 🔥',
    icon_symbol: '🐙',
    market_price: 100.00,
    our_price: 0.89,
    price_egp: 45,
    price_sar: 3.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل ومستقر', 'دعم الدردشة البرمجية Copilot Chat غير المحدود', 'ضمان استبدال سنوي شامل'],
  },
  {
    id: 'copilot_student_prod',
    short_id: 'gh_student',
    brand_id: 'copilot',
    category_id: 'dev',
    name: 'GitHub Student Pack 1y',
    name_ar: 'GitHub Student Developer Pack (سنة)',
    button_title: '🎓 GitHub Student Pack — $0.99 🔥',
    icon_symbol: '🎓',
    market_price: 200.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['يشمل GitHub Copilot مجاناً + نطاق .me مجاني', 'أرصدة سحابية على DigitalOcean و Azure و JetBrains', 'ضمان تفعيل كامل للسنة'],
  },
  {
    id: 'v0_1m_prod',
    short_id: 'v0_1m',
    brand_id: 'v0dev',
    category_id: 'dev',
    name: 'v0.dev Premium 1m',
    name_ar: 'v0.dev by Vercel (شهر)',
    button_title: '⚡ v0.dev Premium — $0.45 🔥',
    icon_symbol: '⚡',
    market_price: 20.00,
    our_price: 0.45,
    price_egp: 22,
    price_sar: 1.8,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['توليد واجهات React / Tailwind / Next.js بنقرة واحدة', 'أرصدة توليد مضاعفة وتصدير مباشر لـ GitHub', 'ضمان استبدال فوري طوال الشهر'],
  },
  {
    id: 'bolt_1m_prod',
    short_id: 'bolt_1m',
    brand_id: 'v0dev',
    category_id: 'dev',
    name: 'Bolt.new Pro 1m',
    name_ar: 'Bolt.new Pro (شهر)',
    button_title: '⚡ Bolt.new Pro — $0.45 🔥',
    icon_symbol: '⚡',
    market_price: 20.00,
    our_price: 0.45,
    price_egp: 22,
    price_sar: 1.8,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['بناء تطبيقات Fullstack كاملة وتشغيلها في المتصفح', 'استخدام نماذج ذكاء اصطناعي متطورة لتطوير الويب', 'ضمان كامل طوال الشهر'],
  },
  {
    id: 'jetbrains_1y_prod',
    short_id: 'jb_1y',
    brand_id: 'jetbrains',
    category_id: 'dev',
    name: 'JetBrains All Products 1y',
    name_ar: 'JetBrains All Products Pack (سنة)',
    button_title: '📦 JetBrains All Pack (سنة) — $0.99 🔥',
    icon_symbol: '📦',
    market_price: 289.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['فتح جميع بيئات JetBrains (IntelliJ, WebStorm, PyCharm, CLion, PhpStorm)', 'تفعيل رسمي أصلي بدون كراكات', 'ضمان استبدال سنوي كامل 100%'],
  },
  {
    id: 'replit_core_prod',
    short_id: 'replit_core',
    brand_id: 'replit',
    category_id: 'dev',
    name: 'Replit Core 1m',
    name_ar: 'Replit Core (شهر)',
    button_title: '🔥 Replit Core — $0.39 🔥',
    icon_symbol: '🔥',
    market_price: 25.00,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['استضافة مشاريع وبوتات وسيرفرات تعمل 24/7 سحابياً', 'مساعد البرمجة الذكي Replit AI', 'ضمان فوري كامل طوال المدة'],
  },

  // ── 9. CANVA PRO ──
  {
    id: 'a1b2c3d4-1111-4444-8888-000000000001',
    short_id: 'a1b2c3d4',
    brand_id: 'canva',
    category_id: 'design',
    name: 'Canva Pro 1y',
    name_ar: 'Canva Pro (سنة كاملة)',
    button_title: '🎨 Canva Pro (سنة) — $0.35 🔥',
    icon_symbol: '🎨',
    market_price: 54.99,
    our_price: 0.35,
    price_egp: 18,
    price_sar: 1.4,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['وصول كامل لأكثر من 100+ مليون قالب وتصميم وعنصر مدفوع', 'إزالة خلفيات الصور والفيديو بنقرة واحدة Magic Remover', 'تفعيل رسمي خاص على إيميلك الشخصي مع ضمان سنة كاملة'],
  },
  {
    id: 'a1b2c3d4-2222-4444-8888-000000000002',
    short_id: 'canvapro_life',
    brand_id: 'canva',
    category_id: 'design',
    name: 'Canva Pro Lifetime',
    name_ar: 'Canva Pro (مدى الحياة VIP)',
    button_title: '👑 Canva Pro (دائم VIP) — $0.79 🔥',
    icon_symbol: '👑',
    market_price: 119.99,
    our_price: 0.79,
    price_egp: 40,
    price_sar: 3.0,
    subscription_duration: 'مدى الحياة (Lifetime)',
    warranty_duration: 'دائم مدى الحياة ضمان ذهبي',
    advantages_ar: ['صلاحية دائمة مدى الحياة بدون أي رسوم تجديد دورية نهائياً', 'فتح كافة أدوات Magic Studio والذكاء الاصطناعي وتنزيل التصاميم بأعلى جودة', 'ترقية رسمية آمنة على حسابك الشخصي مع ضمان ذهبي دائم'],
  },
  {
    id: 'canva_team_prod',
    short_id: 'canva_team',
    brand_id: 'canva',
    category_id: 'design',
    name: 'Canva Pro Team 5 Members',
    name_ar: 'Canva Pro Team (فريق 5 أعضاء)',
    button_title: '👥 Canva Pro Team (5 أعضاء) — $1.19 🔥',
    icon_symbol: '👥',
    market_price: 150.00,
    our_price: 1.19,
    price_egp: 60,
    price_sar: 4.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['إضافة 5 حسابات منفصلة بروابط تفعيل مستقلة', 'مشاركة الخطوط وألوان الهوية وتصاميم الفريق المشتركة', 'ضمان سنوي كامل للفريق'],
  },

  // ── 10. CAPCUT & ADOBE & DESIGN SUITE ──
  {
    id: 'capcut_6m_prod',
    short_id: 'capcut_6m',
    brand_id: 'capcut',
    category_id: 'design',
    name: 'CapCut Pro 6m',
    name_ar: 'CapCut Pro (6 شهور)',
    button_title: '✂️ CapCut Pro (6 شهور) — $0.29 🔥',
    icon_symbol: '✂️',
    market_price: 29.99,
    our_price: 0.29,
    price_egp: 15,
    price_sar: 1.2,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['فتح جميع الفلاتر والمؤثرات والانتقالات المدفوعة', 'تصدير بدقة 4K بدون أي علامة مائية', 'ضمان كامل طوال الـ 6 شهور'],
  },
  {
    id: 'c3d4e5f6-2222-4444-8888-000000000006',
    short_id: 'capcut_pro',
    brand_id: 'capcut',
    category_id: 'design',
    name: 'CapCut Pro 1y',
    name_ar: 'CapCut Pro (سنة كاملة)',
    button_title: '✂️ CapCut Pro (سنة) — $0.39 🔥',
    icon_symbol: '✂️',
    market_price: 49.99,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['ترجمة الفيديوهات التلقائية بالذكاء الاصطناعي مع خطوط عربية', 'مساحة تخزين سحابية لمشاريع المونتاج', 'ضمان استبدال سنوي 100%'],
  },
  {
    id: 'adobe_1m_prod',
    short_id: 'adobe_1m',
    brand_id: 'adobe',
    category_id: 'design',
    name: 'Adobe Creative Cloud 1m',
    name_ar: 'Adobe CC All Apps (شهر)',
    button_title: '🟥 Adobe All Apps (شهر) — $0.49 🔥',
    icon_symbol: '🟥',
    market_price: 59.99,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['جميع برامج أدوبي (Photoshop, Illustrator, Premiere, After Effects)', '100GB تخزين سحابي وميزات الذكاء الاصطناعي Firefly', 'تفعيل على إيميلك الشخصي مع الضمان'],
  },
  {
    id: 'adobe_1y_prod',
    short_id: 'adobe_1y',
    brand_id: 'adobe',
    category_id: 'design',
    name: 'Adobe Creative Cloud 1y',
    name_ar: 'Adobe CC All Apps (سنة كاملة)',
    button_title: '🟥 Adobe All Apps (سنة) — $1.99 🔥',
    icon_symbol: '🟥',
    market_price: 350.00,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 8.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي أصلي كامل لأكثر من 20+ تطبيق أدوبي', 'تحديثات مستمرة وخطوط Adobe Fonts غير محدودة', 'ضمان استبدال سنوي كامل 100%'],
  },
  {
    id: 'figma_1y_prod',
    short_id: 'figma_1y',
    brand_id: 'figma',
    category_id: 'design',
    name: 'Figma Professional 1y',
    name_ar: 'Figma Professional (سنة)',
    button_title: '🖌️ Figma Pro (سنة) — $0.69 🔥',
    icon_symbol: '🖌️',
    market_price: 144.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مشاريع وملفات غير محدودة ومكتبات الفريق Team Libraries', 'أدوات Dev Mode المتقدمة للمطورين', 'ضمان سنوي شامل'],
  },
  {
    id: 'freepik_1y_prod',
    short_id: 'freepik_1y',
    brand_id: 'freepik',
    category_id: 'design',
    name: 'Freepik Premium 1y',
    name_ar: 'Freepik Premium (سنة)',
    button_title: '📸 Freepik Premium (سنة) — $0.49 🔥',
    icon_symbol: '📸',
    market_price: 100.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['تحميل يومي حتى 100 ملف فيكتور وصور PSD حصرية', 'توليد صور ذكاء اصطناعي عبر Freepik AI', 'ضمان استبدال سنوي'],
  },
  {
    id: 'envato_1y_prod',
    short_id: 'envato_1y',
    brand_id: 'envato',
    category_id: 'design',
    name: 'Envato Elements 1y',
    name_ar: 'Envato Elements (سنة)',
    button_title: '🎬 Envato Elements (سنة) — $0.79 🔥',
    icon_symbol: '🎬',
    market_price: 198.00,
    our_price: 0.79,
    price_egp: 40,
    price_sar: 3.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['تحميل غير محدود للقوالب الجاهزة والأكواد والموسيقى والفيديوهات', 'ترخيص تجاري كامل لكافة التصاميم', 'ضمان سنوي 100%'],
  },

  // ── 11. STREAMING & ENTERTAINMENT ──
  {
    id: 'e5f6a7b8-1111-4444-8888-000000000009',
    short_id: 'netflix_4k',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 1m',
    name_ar: 'Netflix 4K UHD (شهر)',
    button_title: '🎬 Netflix 4K (شهر) — $0.25 🔥',
    icon_symbol: '🎬',
    market_price: 15.99,
    our_price: 0.25,
    price_egp: 12,
    price_sar: 1.0,
    subscription_duration: 'شهر كامل (30 يوم)',
    warranty_duration: 'شهر كامل ضمان استبدال',
    advantages_ar: ['أعلى جودة مشاهدة Ultra HD 4K مع صوت محيطي Spatial Audio', 'بروفايل شخصي خاص برمز PIN وسجل مستقل تماماً', 'ضمان استبدال فوري طوال مدة الشهر'],
  },
  {
    id: 'netflix_3m_prod',
    short_id: 'netflix_3m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 3m',
    name_ar: 'Netflix 4K UHD (3 شهور)',
    button_title: '🎬 Netflix 4K (3 شهور) — $0.65 🔥',
    icon_symbol: '🎬',
    market_price: 47.99,
    our_price: 0.65,
    price_egp: 32,
    price_sar: 2.5,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['مشاهدة مستمرة 3 شهور بدون انقطاع وبأعلى دقة 4K', 'يعمل على الشاشات الذكية والجوالات واللابتوب', 'ضمان استبدال فوري'],
  },
  {
    id: 'netflix_6m_prod',
    short_id: 'netflix_6m',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 6m',
    name_ar: 'Netflix 4K UHD (6 شهور)',
    button_title: '🎬 Netflix 4K (6 شهور) — $0.99 🔥',
    icon_symbol: '🎬',
    market_price: 95.99,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['استقرار تام طوال نصف سنة مع بروفايل مقفل بـ PIN', 'دعم تنزيل الأفلام والمشاهدة بدون إنترنت', 'ضمان كامل 100%'],
  },
  {
    id: 'netflix_1y_prod',
    short_id: 'netflix_1y',
    brand_id: 'netflix',
    category_id: 'stream',
    name: 'Netflix 4K UHD 1y',
    name_ar: 'Netflix 4K UHD (سنة كاملة)',
    button_title: '🎬 Netflix 4K (سنة) — $1.49 🔥',
    icon_symbol: '🎬',
    market_price: 190.00,
    our_price: 1.49,
    price_egp: 75,
    price_sar: 6.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل ومستقر بدون أي إغلاقات', 'أعلى باقة بريميوم مع صوت محيطي', 'ضمان ذهبي سنوي شامل 100%'],
  },
  {
    id: 'spotify_3m_prod',
    short_id: 'spotify_3m',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 3m',
    name_ar: 'Spotify Premium (3 شهور)',
    button_title: '🎵 Spotify (3 شهور) — $0.29 🔥',
    icon_symbol: '🎵',
    market_price: 15.00,
    our_price: 0.29,
    price_egp: 15,
    price_sar: 1.2,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['استماع غير محدود لجميع الأغاني والبودكاست بدون إعلانات', 'تنزيل الأغاني بجودة عالية للاستماع بدون نت', 'ترقية على حسابك الشخصي مع الضمان'],
  },
  {
    id: 'spotify_1y_prod',
    short_id: 'spotify_1y',
    brand_id: 'spotify',
    category_id: 'stream',
    name: 'Spotify Premium 1y',
    name_ar: 'Spotify Premium (سنة كاملة)',
    button_title: '🎵 Spotify (سنة) — $0.49 🔥',
    icon_symbol: '🎵',
    market_price: 40.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل على إيميلك الشخصي', 'تشغيل في الخلفية وتخطي غير محدود', 'ضمان سنوي كامل 100%'],
  },
  {
    id: 'youtube_6m_prod',
    short_id: 'yt_6m',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 6m',
    name_ar: 'YouTube Premium + Music (6 شهور)',
    button_title: '▶️ YouTube Premium (6 شهور) — $0.35 🔥',
    icon_symbol: '▶️',
    market_price: 45.00,
    our_price: 0.35,
    price_egp: 18,
    price_sar: 1.4,
    subscription_duration: '6 شهور كاملة',
    warranty_duration: '6 شهور ضمان استبدال',
    advantages_ar: ['مشاهدة فيديوهات يوتيوب بدون أي إعلانات نهائياً', 'تشغيل في الخلفية وميزة صورة داخل صورة PiP', 'يشمل اشتراك YouTube Music مجاناً'],
  },
  {
    id: 'youtube_1y_prod',
    short_id: 'yt_1y',
    brand_id: 'youtube',
    category_id: 'stream',
    name: 'YouTube Premium 1y',
    name_ar: 'YouTube Premium + Music (سنة)',
    button_title: '▶️ YouTube Premium (سنة) — $0.59 🔥',
    icon_symbol: '▶️',
    market_price: 90.00,
    our_price: 0.59,
    price_egp: 30,
    price_sar: 2.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['ترقية رسمية آمنة على حساب جوجل الخاص بك', 'تنزيل الفيديوهات بدقة عالية للمشاهدة بدون إنترنت', 'ضمان سنوي شامل 100%'],
  },
  {
    id: 'disney_1y_prod',
    short_id: 'disney_1y',
    brand_id: 'disney',
    category_id: 'stream',
    name: 'Disney+ Premium 1y',
    name_ar: 'Disney+ Premium (سنة كاملة)',
    button_title: '⭐ Disney+ (سنة) — $0.49 🔥',
    icon_symbol: '⭐',
    market_price: 80.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['أفلام ديزني ومارفل وستار وورز بدقة 4K', 'دبلجة وترجمة عربية احترافية لجميع الأعمال', 'ضمان سنوي كامل'],
  },
  {
    id: 'shahid_1y_prod',
    short_id: 'shahid_1y',
    brand_id: 'shahid',
    category_id: 'stream',
    name: 'Shahid VIP Sports 1y',
    name_ar: 'Shahid VIP شامل الرياضة (سنة)',
    button_title: '🍿 Shahid VIP رياضة (سنة) — $0.69 🔥',
    icon_symbol: '🍿',
    market_price: 99.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['بث مباشر لمباريات دوري روشن والبطولات الرياضية', 'أحدث مسلسلات وأفلام شاهد الأصلية بدقة Full HD', 'ضمان سنوي كامل 100%'],
  },
  {
    id: 'discord_3m_prod',
    short_id: 'discord_3m',
    brand_id: 'discord',
    category_id: 'stream',
    name: 'Discord Nitro 3m',
    name_ar: 'Discord Nitro Boost (3 شهور)',
    button_title: '🎮 Discord Nitro (3 شهور) — $0.49 🔥',
    icon_symbol: '🎮',
    market_price: 30.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['2 سيرفر بوست مجاني مع خصم 30% على البوستات الإضافية', 'استخدام الإيموجي والستيكرز المتحركة في كل السيرفرات', 'بث ألعاب بجودة 4K و 60 FPS ورفع ملفات حتى 500MB'],
  },
  {
    id: 'discord_1y_prod',
    short_id: 'discord_1y',
    brand_id: 'discord',
    category_id: 'stream',
    name: 'Discord Nitro 1y',
    name_ar: 'Discord Nitro Boost (سنة كاملة)',
    button_title: '🎮 Discord Nitro (سنة) — $0.99 🔥',
    icon_symbol: '🎮',
    market_price: 99.00,
    our_price: 0.99,
    price_egp: 50,
    price_sar: 4.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي كامل شارة نيترو مميزة وبروفايل مخصص', 'شارة الداعم ودعم البث الفائق', 'ضمان سنوي كامل 100%'],
  },
  {
    id: 'tgprem_3m_prod',
    short_id: 'tg_3m',
    brand_id: 'tgprem',
    category_id: 'stream',
    name: 'Telegram Premium 3m',
    name_ar: 'Telegram Premium (3 شهور)',
    button_title: '✈️ Telegram Premium (3 شهور) — $0.69 🔥',
    icon_symbol: '✈️',
    market_price: 15.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: '3 شهور كاملة',
    warranty_duration: '3 شهور ضمان استبدال',
    advantages_ar: ['رفع ملفات بحجم يصل إلى 4GB وسرعة تنزيل فائقة بدون حدود', 'تحويل الرسائل الصوتية إلى نصوص مكتوبة فوراً', 'شارة النجمة التوثيقية وإيموجي وتفاعلات غير محدودة'],
  },
  {
    id: 'tgprem_1y_prod',
    short_id: 'tg_1y',
    brand_id: 'tgprem',
    category_id: 'stream',
    name: 'Telegram Premium 1y',
    name_ar: 'Telegram Premium (سنة كاملة)',
    button_title: '✈️ Telegram Premium (سنة) — $1.99 🔥',
    icon_symbol: '✈️',
    market_price: 45.00,
    our_price: 1.99,
    price_egp: 100,
    price_sar: 8.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['اشتراك سنوي رسمي مفعل كهدية Gift على يوزرك مباشرة', 'إلغاء الإعلانات بالكامل في القنوات ومضاعفة الحدود للقنوات والمجموعات', 'ضمان سنوي شامل 100%'],
  },

  // ── 12. SECURITY & VPNS ──
  {
    id: 'nordvpn_1y_prod',
    short_id: 'nord_1y',
    brand_id: 'nordvpn',
    category_id: 'vpn',
    name: 'NordVPN Plus 1y',
    name_ar: 'NordVPN Plus (سنة كاملة)',
    button_title: '🛡️ NordVPN (سنة) — $0.49 🔥',
    icon_symbol: '🛡️',
    market_price: 60.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['أكثر من 6000 سيرفر فائق السرعة في 111 دولة', 'حماية Threat Protection ضد الإعلانات والمواقع الضارة', 'دعم حتى 10 أجهزة في وقت واحد'],
  },
  {
    id: 'nordvpn_2y_prod',
    short_id: 'nord_2y',
    brand_id: 'nordvpn',
    category_id: 'vpn',
    name: 'NordVPN Plus 2y',
    name_ar: 'NordVPN Plus (سنتين كاملتين)',
    button_title: '🛡️ NordVPN (سنتين) — $0.79 🔥',
    icon_symbol: '🛡️',
    market_price: 110.00,
    our_price: 0.79,
    price_egp: 40,
    price_sar: 3.0,
    subscription_duration: 'سنتين كاملتين (24 شهر)',
    warranty_duration: 'سنتين ضمان استبدال كامل',
    advantages_ar: ['أطول مدة اشتراك حماية مستقرة 24 شهر', 'سرعات فائقة تدعم التورنت والألعاب وفتح المواقع المحجوبة', 'ضمان ذهبي شامل سنتين'],
  },
  {
    id: 'expressvpn_1y_prod',
    short_id: 'exp_1y',
    brand_id: 'expressvpn',
    category_id: 'vpn',
    name: 'ExpressVPN Ultra 1y',
    name_ar: 'ExpressVPN Ultra (سنة)',
    button_title: '⚡ ExpressVPN (سنة) — $0.69 🔥',
    icon_symbol: '⚡',
    market_price: 99.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['بروتوكول Lightway الحصري لأعلى سرعات واستقرار', 'تخطي حجب قوي يعمل في كافة الدول والشبكات الصعبة', 'ضمان استبدال سنوي كامل'],
  },
  {
    id: 'surfshark_2y_prod',
    short_id: 'surf_2y',
    brand_id: 'surfshark',
    category_id: 'vpn',
    name: 'Surfshark One 2y',
    name_ar: 'Surfshark One (سنتين)',
    button_title: '🦈 Surfshark One (سنتين) — $0.59 🔥',
    icon_symbol: '🦈',
    market_price: 70.00,
    our_price: 0.59,
    price_egp: 30,
    price_sar: 2.5,
    subscription_duration: 'سنتين كاملتين (24 شهر)',
    warranty_duration: 'سنتين ضمان استبدال كامل',
    advantages_ar: ['أجهزة غير محدودة Unlimited Devices في نفس الوقت', 'مضاد فيروسات مدمج وحماية كاملة للهوية CleanWeb', 'ضمان استبدال شامل'],
  },
  {
    id: 'kaspersky_1y_prod',
    short_id: 'kasp_1y',
    brand_id: 'kaspersky',
    category_id: 'vpn',
    name: 'Kaspersky Total Security 1y',
    name_ar: 'Kaspersky Total Security (سنة)',
    button_title: '🔐 Kaspersky Total (سنة) — $0.49 🔥',
    icon_symbol: '🔐',
    market_price: 50.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['مفتاح ترخيص رقمي أصلي لتفعيل البرنامج رسمياً', 'حماية فيروسات وفدية وجدار ناري قوي للمعاملات البنكية', 'ضمان تفعيل كامل 100%'],
  },

  // ── 13. PRODUCTIVITY & OFFICE ──
  {
    id: 'notion_1y_prod',
    short_id: 'notion_1y',
    brand_id: 'notion',
    category_id: 'prod',
    name: 'Notion AI Plus 1y',
    name_ar: 'Notion AI Plus (سنة كاملة)',
    button_title: '📝 Notion AI Plus (سنة) — $0.59 🔥',
    icon_symbol: '📝',
    market_price: 120.00,
    our_price: 0.59,
    price_egp: 30,
    price_sar: 2.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['استخدام ذكاء اصطناعي غير محدود لكتابة وتلخيص الملاحظات', 'رفع ملفات غير محدود ومزامنة سحابية بين كل الأجهزة', 'ضمان سنوي شامل'],
  },
  {
    id: 'grammarly_1y_prod',
    short_id: 'gram_1y',
    brand_id: 'grammarly',
    category_id: 'prod',
    name: 'Grammarly Premium 1y',
    name_ar: 'Grammarly Premium (سنة)',
    button_title: '🔤 Grammarly Premium (سنة) — $0.39 🔥',
    icon_symbol: '🔤',
    market_price: 144.00,
    our_price: 0.39,
    price_egp: 20,
    price_sar: 1.5,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['تصحيح قواعد متقدم وإعادة صياغة الجمل الإنجليزية باحترافية', 'فحص الاقتباس والانتحال الأدبي Plagiarism Checker', 'ضمان سنوي كامل'],
  },
  {
    id: 'duolingo_1y_prod',
    short_id: 'duo_1y',
    brand_id: 'duolingo',
    category_id: 'prod',
    name: 'Duolingo Super 1y',
    name_ar: 'Duolingo Super (سنة كاملة)',
    button_title: '📚 Duolingo Super (سنة) — $0.35 🔥',
    icon_symbol: '📚',
    market_price: 84.00,
    our_price: 0.35,
    price_egp: 18,
    price_sar: 1.4,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['قلوب وطاقة غير محدودة للتعلم السريع بدون توقف', 'إلغاء جميع الإعلانات واختبارات مراجعة الأخطاء المخصصة', 'ترقية رسمية على حسابك مع الضمان'],
  },
  {
    id: 'm365_1y_prod',
    short_id: 'm365_1y',
    brand_id: 'm365',
    category_id: 'prod',
    name: 'Microsoft 365 + 1TB OneDrive',
    name_ar: 'Microsoft 365 + 1TB OneDrive (سنة)',
    button_title: '📊 Microsoft 365 + 1TB (سنة) — $0.49 🔥',
    icon_symbol: '📊',
    market_price: 99.00,
    our_price: 0.49,
    price_egp: 25,
    price_sar: 2.0,
    subscription_duration: 'سنة كاملة (12 شهر)',
    warranty_duration: 'سنة كاملة ضمان استبدال',
    advantages_ar: ['برامج Office كاملة (Word, Excel, PowerPoint, Outlook)', '1000GB سعة تخزين سحابية خاصة على OneDrive', 'تفعيل رسمي حتى 5 أجهزة مع الضمان'],
  },
  {
    id: 'win11_pro_prod',
    short_id: 'win11_pro',
    brand_id: 'win11',
    category_id: 'prod',
    name: 'Windows 11 Pro Retail Key',
    name_ar: 'Windows 11 Pro Retail (مفتاح أصلي دائم)',
    button_title: '🪟 Windows 11 Pro (دائم) — $0.69 🔥',
    icon_symbol: '🪟',
    market_price: 199.00,
    our_price: 0.69,
    price_egp: 35,
    price_sar: 2.8,
    subscription_duration: 'مدى الحياة (Lifetime)',
    warranty_duration: 'دائم مدى الحياة ضمان ذهبي',
    advantages_ar: ['مفتاح تفعيل رقمي أصلي معتمد من مايكروسوفت 25 رمز', 'تفعيل دائم مدى الحياة يقبل التحديثات وإعادة التثبيت', 'ضمان تفعيل ذهبي 100%'],
  },
];

export function getCategoryById(id) {
  return STORE_CATEGORIES.find((c) => c.id === id);
}

export function getBrandsByCategory(categoryId) {
  return STORE_BRANDS.filter((b) => b.category_id === categoryId);
}

export function getBrandById(brandId) {
  return STORE_BRANDS.find((b) => b.id === brandId);
}

export function getProductsByBrand(brandId) {
  return STORE_CATALOG.filter((p) => p.brand_id === brandId);
}

export function getProductByShortIdOrSlug(identifier) {
  if (!identifier) return null;
  return STORE_CATALOG.find(
    (p) => p.short_id === identifier || p.id === identifier || p.slug === identifier
  );
}
